### ISSUE TITLE
Page "Nouvelle Étude"

### ISSUE THREAD

**Issue by GChabahABC** [ABC-TransitionBasCarbone/bilan-carbone#10]
## Contexte

Cette page s'affiche lorsque l'utilisateur clique sur "Nouvelle étude". L'utilisateur doit définir les paramètres de l'étude : 
- Quel est le nom de l'étude
- Sur quelle organisation porte l'étude et à quoi ressemble cette organisation (nombre de sites, type de sites, adresses, informations administratives, etc)
- Sur quel périmètre temporel s'étend l'étude 
- Quel est le type de Bilan Carbone® effectué : Bilan Carbone® Initial/Bilan Carbone® Standard/Bilan Carbone® Avancé
- Quel exports sont souhaités et quels mode de contrôle sont à utiliser pour ces exports
- Est-ce que l'étude est privée ou publique (définit qui peut y accéder sans droits spécifiques au sein de l'organisation)

## Tests d'acceptance 

Cette page est une fusion entre les différentes pages que l'on peut actuellement atteindre via le bouton "Nouvelle Étude" (Nouvelle Étude + Nouvelle Étude > Nouvelle organisation + Nouvelle Étude > Suivant). 

Les champs affichés sont les suivants : 
Nom de l'étude : [Champ à remplir par l'utilisateur]
Organisation étudiée : [Pour les utilisateurs classiques, leur organisation est sélectionnée d'office ; pour les C&R, un menu déroulant permettant de sélectionner l'organisation voulue apparait : ils sélectionnent alors une organisation préexistante, ou "Nouvelle organisation"] 
Période étudiée : [Champs à remplir par l'utilisateur]
Type de Bilan Carbone® : [Menu déroulant : Bilan Carbone® Initial/Bilan Carbone® Standard/Bilan Carbone® Avancé]
Statut de l'étude : [Menu déroulant : Publique/Privée]

Deux boîtes apparaissent sous les champs à remplir : 

1. Une boîte "Organisation", basée sur la configuration actuelle de la page du même nom : Si une organisation est sélectionnée, les informations apparaissent, si "Nouvelle organisation" est sélectionnée, les champs sont vides et à remplir. 

Quelques modifications par rapport à la page actuelle : 
- Remplacer "Entités" par "Sites"
- Les champs "Adresse (suite)"*2, "Site web", "Autre ID", "Num TVA" ne sont pas à reprendre, la coche d'entité principale non plus. 
- Un champ affichant le nom/permettant de nommer l'organisation doit apparaitre. 
- Les champs "Hiérarchie" ne doivent plus apparaitre. 
- Les onglets "Données financières" et "Employés peuvent être fusionnés avec l'onglet "Coordonnées" en intégrant un champ pour le Chiffre d'Affaire HT du site et un champ pour son nombre d'ETP. L'onglet serait alors renommé : "Données génériques". 
- L'onglet "Données opérationnelles" est à reprendre, mais seulement avec l'ajout des produits et services. 
- L'organisation n'est créée que lorsque l'on clique sur "Enregistrer". Pas de possibilité de modifier une organisation existante ici pour le moment, mais ce sera à prévoir à l'avenir (il faut encore que je réfléchisse aux sécurités à mettre avant modification, pour les cas où d'autres études sont sur la même organisation).

2. Une boîte "Exports souhaités", qui reprend la configuration actuelle de la page "Nouvelle Étude > Suivant" avec quelques modifications : "BEGES-r 2023" est remplacé par "Bilan GES Règlementaire" ; "GHG P" est remplacé par "GHG Protocol" ; Le menu déroulant "Mode de contrôle" est placé par défaut sur "Contrôle opérationnel"

Les éléments devant être repris (attention aux onglets sur la page organisation) : ![Image](https://github.com/user-attachments/assets/9df26240-5c4f-4feb-9c16-3a924f4b1831)

## Infos de test

Vérifier qu'il est possible de : 
- Créer une étude portant sur son organisation en tant qu'utilisateur classique 
- Créer une étude portant sur n'importe quelle organisation existante en tant qu'utilisateur C&R 
- Créer une étude portant sur une nouvelle organisation en tant qu'utilisateur C&R 

## Stratégie technique 

[...]

**Comment by cmolle** [comment]
@GChabahABC Petites questions :
- Ici du coup il faut bien reprendre uniquement l'onglet qui est visible sur la capture que tu as pris et pas les autres onglets de la partie organisation ? 
- Est-ce qu'on ne pourrait pas imaginer plutôt une modale pour ajouter une nouvelle organisation ? Et uniquement afficher le nom des entités de l'orga sur la page de création de l'étude ? OU est-ce qu'il y a besoin d'afficher toutes les informations de l'organisation ?

**Comment by GChabahABC** [comment]
@cmolle 

- Non, il faut reprendre les informations de tous les onglets mais je pense qu'on peut garder uniquement deux onglets : "Coordonnées" qu'on peut renommer "Données génériques" et "Données opérationnelles" et dans "Données Génériques" on rajoute le CA et les ETP aux informations déjà demandées, histoire d'éviter d'avoir quatre onglets !
- On peut, mais du coup deux choses doivent pouvoir donner accès à la modale : 1) Sélectionner "Nouvelle Organisation" dans le menu déroulant et 2) Cliquer sur une icône ou un bouton "Modifier l'organisation" (Pas besoin de le faire maintenant car il faudra qu'on gère ce que ça change ou pas dans les études déjà faites), mais à garder en tête !
