### ISSUE TITLE
ETQ utilisateur, j'ai accès à un selecteur pour ajouter une personne de mon organisation à une étude

### ISSUE THREAD

**Issue by cmolle** [ABC-TransitionBasCarbone/bilan-carbone#102]
## Contexte

La page "Équipe Projet" sert à définir les droits des utilisateurs plus finement que la page "Gestion de l'équipe", en pouvant définir des droits spécifiques au niveau de l'étude. Elle permet également d'ajouter des utilisateurs qui ne sont pas membre de l'organisation à une étude spécifique. Cette fonctionnalité est utilisée pour inviter des clients, partenaires, etc, à prendre part à une étude spécifique. L'ajout pourrait se passer comme suit : 
- L'utilisateur peut rajouter quelqu'un de son organisation via une liste déroulante
- L'utilisateur peut rajouter quelqu'un en tapant son mail et là :
1. Si la personne est déjà au sein de l'organisation (i.e elle aurait pu être ajoutée via la liste déroulante) > Elle est ajoutée comme si c'était fait via la liste
2. Si la personne est utilisatrice du BC+ mais au sein d'une autre organisation, un pop-up s'ouvre avec un message type "La personne que vous souhaitez ajouter est utilisatrice du BC+ au sein d'une autre organisation que la votre. Souhaitez-vous vraiment l'ajouter à cette étude ?"
3. Si la personne est externe au BC+, il faut qu'un message s'affiche disant "Cette personne n'est pas utilisatrice du BC+, vous ne pourrez donc lui donner un accès à l'étude qu'avec les droits de consultation ou de contribution." >Et du coup là plus que ces deux droits de sélectionnables.

Ici on ne s'occupe que de la partie ajout des utilisateurs de son organisation. La fonctionnalité a déjà été codé mais il y a aujourd'hui un input, il faudrait un selecteur. La gestion de ce selecteur pour les autres cas sera fait dans les prochains tickets #34 et #36 

## Tests d'acceptance
Sur la page d'ajout d'un utilisateur à une étude, à la place de l'input actuel j'ai un selecteur qui me permet de sélectionner un utilisateur de mon organisation. Il faut que je puisse filtrer la sélection sur le nom, prénom ou mail de l'utilisateur. 

## Infos de test

Comment bien tester ce ticket ?

## Stratégie technique

Quelle strat technique adopter pour ce ticket ?

**Comment by fortinlouis** [comment]
Ajout warning : n'est pas membre ou n'est pas dans votre orga

Peut être sujet à évolution à l'avenir (discussion en cours avec Gabriel)

**Comment by cmolle** [comment]
@fortinlouis la PR semble fusionnée ? Où en est ce ticket ?

**Comment by fortinlouis** [comment]
> @fortinlouis la PR semble fusionnée ? Où en est ce ticket ?

Mergé, je me suis mis sur le fait de pouvoir sélectionner des nom/prénom (ticket #106)
