### ISSUE TITLE
ETQ utilisateur de C&R, mes études sont regroupées en dossier

### ISSUE THREAD

**Issue by cmolle** [ABC-TransitionBasCarbone/bilan-carbone#103]
## Contexte
On veut que les organisations C&R aient toutes les études d'une organisation regroupées dans un même dossier. 

Il faut donc changer leur page d'accueil : le bandeau à droite n'est pas les études mais un dossier par organisation. Le bouton à droite n'est donc plus "nouvelle étude" mais nouvelle organisation et renvoie sur la page de création d'une nouvelle organisation. 

Lorsque la nouvelle organisation, ils arrivent sur la page d'une organisation pour un C&R : 
- Le breadcrumbs avec le nom du dossier 
- Le bandeau à droite contenant les études (le même que celui présent sur la page d'accueil des orgas classiques) en plein écran pour l'instant
- Graphiques résumés de la dernière étude en haut

## Tests d'acceptance
- Si je me connecte en tant qu'utilisateur d'une orga C&R j'ai bien une page d'accueil différente, telle que définie plus haut
- Si je me connecte en tant qu'utilisateur non C&R j'ai toujours la page d'accueil actuelle

## Infos de test

Comment bien tester ce ticket ?

## Stratégie technique

Quelle strat technique adopter pour ce ticket ?

**Comment by cmolle** [comment]
@GChabahABC je me dis que pour l'instant pour les dossiers on peut uniquement demandé aux utilisateurs de donner un nom mais de ne donner aucune contrainte d'avoir forcément une seule orga liée, comme ca cela leur permettra de faire des dossiers par projet par exemple (ou en tout cas d'être libre d'en faire ce qu'ils veulent). Si on voit par la suite que c'est trop compliqué de laisser libre car cela implique trop de complexité niveau code on ajoutera des contraintes. 
Qu'en penses-tu ?

**Comment by GChabahABC** [comment]
@cmolle Je pense qu'il vaut mieux contraindre direct sauf si c'est plus difficile à coder : Dans tous les cas on sait déjà qu'on va vouloir avoir une vision plan de transition au niveau de l'organisation, du coup je vois pas comment on gère ça si on a plusieurs orga dans un même dossier, on pourra rien afficher sur la page "dossier étude" ?

**Comment by cmolle** [comment]
Il me semble qu'on avait parlé de potentiellement laisser la possibilité de faire par projet, du coup on pourrait laisser ouvert le fait de faire plusieurs BC dans un même dossier. Et il pourrait y avoir par contre qu'un seul plan de transition pour le projet ? Ou en tout cas un principal pour que ca s'affiche sur la page d'accueil ?

**Comment by cmolle** [comment]
Vu ensemble : sur la page d'accueil il y a un dossier par organisation créée

**Comment by GChabahABC** [comment]
@fortinlouis Hello, sur ce ticket il manque juste le fait que dans le dossier dédié à une organisation, les graphiques reprennent bien les éléments de la dernière étude portant sur l'organisation. J'ai testé avec cette orga (cf capture), dans les deux études j'ai mis des données et j'ai bien les graphiques dans chaque étude, mais sur la page récap de l'orga, les graphiques ne reprennent pas les données de l'étude la plus récente. Je pense qu'à l'époque du ticket les graphiques n'existaient pas encore, d'où le manque. 

![Image](https://github.com/user-attachments/assets/2e4c8156-7983-46ac-80ca-07cde44157e0)

**Comment by fortinlouis** [comment]
> @fortinlouis Hello, sur ce ticket il manque juste le fait que dans le dossier dédié à une organisation, les graphiques reprennent bien les éléments de la dernière étude portant sur l'organisation. J'ai testé avec cette orga (cf capture), dans les deux études j'ai mis des données et j'ai bien les graphiques dans chaque étude, mais sur la page récap de l'orga, les graphiques ne reprennent pas les données de l'étude la plus récente. Je pense qu'à l'époque du ticket les graphiques n'existaient pas encore, d'où le manque.
> 
>
@GChabahABC Je ne pense pas que ça soit une histoire de date, mais de récupération de l'étude. Je n'ai pas eu ce cas lors du dev. Est ce qu'on peut regarder ensemble à un moment ?

**Comment by GChabahABC** [comment]
Sur la page d'accueil, les graphiques qui s'affichent doivent bien correspondre par défaut à mon organisation, donc :
- Si je suis utilisateur classique, c'est la dernière étude sur mon organisation  qui est affichée en page d'accueil, et après les graphiques de chaque études sont affichés seulement dans les études en question 
- Si je suis utilisateur C&R, c'est la dernière étude sur mon organisation qui est affichée en page d'accueil, et ensuite si j'ai travaillé pour deux organisations A & B, quand je vais dans le dossier de l'organisation A j'ai la dernière étude sur l'organisation A, et dans celui de B, la dernière étude sur l'organisation B.

On réfléchira plus tard à mettre un menu de sélection de ce qu'on veut afficher à l'accueil, mais pas prio du tout.

**Comment by fortinlouis** [comment]
Ces soucis ont été gérés dans la PR https://github.com/ABC-TransitionBasCarbone/bilan-carbone/pull/231, avec le respect de la consigne que tu as cité. On en a profité pour ajouter le nom de l'étude affichée, comme ça aucun doute sur l'étude concernée
