### ISSUE TITLE
Renommer les Emissions en EmissionFactors

### ISSUE THREAD

**Issue by desoindx** [ABC-TransitionBasCarbone/bilan-carbone#104]
## Contexte

Donner quelques phrases de contexte, dans quel cadre s'inscrit ce ticket

## Tests d'acceptance

Quelles sont les fonctionnalités à développer dans ce ticket

## Infos de test

Comment bien tester ce ticket ?

## Stratégie technique

Quelle strat technique adopter pour ce ticket ?

**Comment by cmolle** [comment]
@desoindx la PR semble être fusionnée, où en est ce ticket ?
