### ISSUE TITLE
ETQ utilisateur, je veux pouvoir exporter les sources d'émissions d'un sous-poste de mon bilan carbone

### ISSUE THREAD

**Issue by cmolle** [ABC-TransitionBasCarbone/bilan-carbone#107]
## Contexte
Certains utilisateurs apprécient le fait de pouvoir exporter les données entrées dans le BC + au format excel afin de faire d'autres calculs, de vérifier certaines données ... Il faut donc qu'ils puissent facilement exporter les données. 

Ici on s'intéresse à un export à la maille du sous poste. D'autres tickets à venir pour la maille poste et bilan carbone globale. Les exports seront aussi présents pour d'autres fonctionnalités tel que l'export au format réglémentaire BEGES.

## Tests d'acceptance
En haut à gauche d'un sous-poste, j'ai l'icone FileDownload. Lorsque je clique dessus, cela télécharge un fichier au format csv (ouvrable avec Excel ou autres logiciels similaires) nom_du_bilan_poste_sous_poste_YYYY_MM_DD où la date est la date du jour. 
Dans cet excel on a une seule feuille avec toutes les sources d'émissions pour le sous poste listées avec les informations suivantes : 
- Validation de la source d'émission
- Date butoire
- Nom de la source d'émission
- Caractérisation de la source d'émission
- valeur de la source d'émission
- commentaire de la source d'émission
- Nom du FE (facteur d'émission)
- Valeur du FE
- Source du FE
- Colonnes sur la qualité de la source d'émission
- Colonnes sur la qualité du FE

A la fin du tableau, on veut une dernière ligne avec le total des émissions et de l'incertitude pour ce sous poste 

## Infos de test

Comment bien tester ce ticket ?

## Stratégie technique

Quelle strat technique adopter pour ce ticket ?

**Comment by cmolle** [comment]
A ajouter: une ligne pour avoir le total

**Comment by GChabahABC** [comment]
@fortinlouis Mêmes commentaires que sur l'autre ticket (je les remets à chaque fois au cas où) :

Il faudrait exporter les informations liées à la donnée d'activité (valeur, unité, source, qualité)
Il faudrait exporter l'unité pour la source d'émission, la donnée d'activité et le FE
La caractérisation s'exporte en anglais de mon côté (j'ai "Operated" pour "Opéré")
