### ISSUE TITLE
ETQ utilisateur, je veux exporter toutes les sources d'émissions de mon bilan carbone

### ISSUE THREAD

**Issue by cmolle** [ABC-TransitionBasCarbone/bilan-carbone#109]
## Contexte
Certains utilisateurs apprécient le fait de pouvoir exporter les données entrées dans le BC + au format excel afin de faire d'autres calculs, de vérifier certaines données ... Il faut donc qu'ils puissent facilement exporter les données.

Ici on s'intéresse à un export à la maille du bilan carbone. Les exports seront aussi présents pour d'autres fonctionnalités tel que l'export au format réglémentaire BEGES.

## Tests d'acceptance
A côté du nom du bilan carbone, j'ai l'icone FileDownload, si je clique dessus je télécharge un csv nom_du_bc_YYYY_MM_DD. 
J'ai les mêmes colonnes que pour l'excel poste avec en + une colonne "poste". 

A la fin du tableau, on veut une dernière ligne avec le total des émissions et de l'incertitude pour ce bilan carbone

## Infos de test

Comment bien tester ce ticket ?

## Stratégie technique

Quelle strat technique adopter pour ce ticket ?

**Comment by GChabahABC** [comment]
@fortinlouis Mêmes commentaires que sur l'autre ticket (je les remets à chaque fois au cas où) :
- Il faudrait exporter les informations liées à la donnée d'activité (valeur, unité, source, qualité)
- Il faudrait exporter l'unité pour la source d'émission, la donnée d'activité et le FE
- La caractérisation s'exporte en anglais de mon côté (j'ai "Operated" pour "Opéré")
