### ISSUE TITLE
ETQ utilisateur, j'ai accès à une nouvelle page lorsque j'accède à une étude

### ISSUE THREAD

**Issue by cmolle** [ABC-TransitionBasCarbone/bilan-carbone#110]
## Contexte
 Lorsque les utilisateurs ouvrent une étude, on veut qu'ils puissent avoir certaines informations sur leur bilan carbone ainsi que le résumé des émissions par poste.  
![image](https://github.com/user-attachments/assets/b134bf28-a6d9-4a92-9903-ccb68f29fa8e)

Ce ticket comporte beaucoup de changements. Il est possible de le découper en plusieurs tickets (notamment pour la partie export si les tickets associés aux exports ne sont pas encore fait)

## Tests d'acceptance
- Lorsque je clique sur une étude j'arrive sur la page d'accueil de l'étude 
     - J'ai les informations globales de ce bilan carbone 
     - Deux graphiques : 
         - Un premier qui résume toutes les émissions réparties par poste. Un bouton me permet d'extraire les données sous excel
         - Un second qui résume toutes les émissions réparties par sous poste. Le nom du poste est sous forme de sélecteur et je peux sélectionner n'importe quel poste de mon BC. Un bouton me permet d'extraire les données du poste
     - Un bandeau de navigation spécifique à mon étude (pour l'instant toutes les cases sont grisées et ne fonctionnent pas) : les différences par rapport à l'image présente : 
         - On ne met pas les icones sablier 
         - Pour Cadrage on met un sous titre "gestion de l'équipe"
         - Pour Comptabilisation on met deux sous-titre sur lesquels il faut cliquer pour être redirigé : "Saisie" et "Résultat"

On affiche tous les postes et sous poste meme si ils sont à 0. Si pas la place on les mets les uns au dessus de l'autre

Finalement on change le menu par un side menu que l'on peut collapse

**Comment by cmolle** [comment]
Vu avec Gabriel pour les redirection : 
- Cadrage : on ajoute un sous titre "gestion de l'équipe" 
- Comptabilisation on met deux sous titre saisie et résultat qui permet de renvoyer vers deux pages différentes

**Comment by GChabahABC** [comment]
@cmolle 

Juste un petit détail là-dessus, il manque le sous-titre "Gestion de l'équipe" pour cadrage, qu'on comprenne bien ce qu'il y a dedans. D'ailleurs pour que ce soit pas confus vis-à-vis du bouton "Équipe" dans le bandeau du haut, est-ce qu'on renommerait pas ce "Équipe" du bandeau en "Utilisateurs"/"Gestion des utilisateurs" ?

**Comment by cmolle** [comment]
Vu ensemble : Pour le nom de l'onglet Equipe, on attend la démo pour statuer sur un nom

**Comment by cmolle** [comment]
@GChabahABC je te laisse regarder ce ticket vu que c'est moi qui l'ai dev ^^
