### ISSUE TITLE
ETQ utilisateur, je peux accéder à une page de résultat

### ISSUE THREAD

**Issue by cmolle** [ABC-TransitionBasCarbone/bilan-carbone#112]
## Contexte
Une fois les sources d'émission renseignées, l'utilisateur va vouloir avoir accès à une page de résultat qui lui permet d'avoir de manière aggregée les résultats. Il va falloir faire plusieurs écrans, un par export. On veut également qu'ils aient accès à des graphiques que l'on définira plus tard. 

Comme pour les différents affichages lors de la saisie des données sources, on a ici un toggle indiquant : 
- Global
- BEGES
- GHGP
- ISO 14069 

(avec uniquement les exports choisis lors de la configuration) 

## Tests d'acceptance

Ajouter une page avec un tableau similaire à celui actuellement présent sur le BC + : 
- On a 2 colonnes par sites de l'organisation, 1 pour le total des émissions, 1 pour le total des incertitudes + 2 colonnes pour la somme sur tous les sites de l'organisation 
- On a au départ, 1 ligne par poste. Les lignes peuvent être étendues pour avoir le détail par sous poste. (on pourrait utiliser ceci https://mui.com/material-ui/react-table/#collapsible-table)

Ajouter le toggle pour naviguer entre les vues et afficher uniquement un hello world sur les autres export pour l'instant

## Infos de test

Comment bien tester ce ticket ?

## Stratégie technique

Quelle strat technique adopter pour ce ticket ?

**Comment by GChabahABC** [comment]
@cmolle Je mettrais bien toutes ces infos directement dans la page d'accueil de l'étude avec des boutons pour manipuler les graphiques et pouvoir switch entre des graphes, des tableaux, des formats etc, au lieu de faire une page dédiée. Est-ce que tu penses que ce serait trop complexe ? Pour la plupart des utilisateurs notamment les entreprises classiques, je pense que les graphiques seront bien plus parlants, seuls quelques BE voudront une config "tableau". Bref à mon avis ce serait cool d'avoir un truc relativement succinct et seulement sur la page "accueil" de l'étude, mais très modulaire !

**Comment by cmolle** [comment]
Vu ensemble : on garde les résultats à part et sur la page principale on met des graphiques. 
A voir à l'usage si on voudra changer

**Comment by GChabahABC** [comment]
@desoindx 

Micro-détail ici, si on peut renommer "Consolidé" dans le menu déroulant de sélection du format (BC vs BEGES vs ISO etc) en "Bilan Carbone®", ce sera plus clair pour les utilisateurs.

Il manque la partie gestion des résultats par entités mais on refera un ticket je pense.
