### ISSUE TITLE
ETQ admin, je peux modifier une organisation

### ISSUE THREAD

**Issue by cmolle** [ABC-TransitionBasCarbone/bilan-carbone#152]
## Contexte
On a une page de gestion d'une organisation mais pour l'instant on ne peut pas la modifier. Il faudrait que les utilisateurs admin puissent la modifier, ajouter des entités... 

## Tests d'acceptance
- Quand j'appuie sur le bouton modifier de la page organisation, j'arrive sur une nouvelle page de formulaire pré-remplli sur laquelle je peux modifier : 
     - le nom
     - les entités 
          - leur noms 
          - leur etp 
          - leur ca
   Je peux également supprimer une entité ou en ajouter une (si possible ne pas faire une nouvelle page pour la création d'une entité, faire plutôt un tableau dans lequel on peut ajouter des lignes)

## Infos de test

Comment bien tester ce ticket ?

## Stratégie technique

Quelle strat technique adopter pour ce ticket ?

**Comment by GChabahABC** [comment]
@desoindx 

Micro-détail ici, une fois qu'on a cliqué sur "Modifier", le bouton pour valider la modification s'appelle aussi "modifier", ce qui n'est pas très clair, je mettrais tout bêtement "Valider la modification" sur ce bouton. 

![Image](https://github.com/user-attachments/assets/4cf08ed2-e549-4072-8460-75e31749858e)
