### ISSUE TITLE
ETQ utilisateur, je peux sélectionner des entités pour une étude

### ISSUE THREAD

**Issue by cmolle** [ABC-TransitionBasCarbone/bilan-carbone#157]
## Contexte
Une organisation peut décider de faire des bilans carbone seulement pour certains sites d'une organisation. Il faut donc leur laisser la possibilité de les sélectionner et de modifier les sites concernés par l'étude. 

## Tests d'acceptance
Quand je créé une étude, je peux sélectionner les sites concernés par mon bilan carbone. Je peux également modifier les sites concernés dans la partie périmètre de mon bilan. 

Dans la page saisie des données et résultats, j'ai un sélecteur en haut de la page qui me permet d'afficher les pages seulement pour un site ou pour toute l'organisation (le choix de toute l'orga est uniquement possible pour la page de résultat).  On garde l'information quand on change de page du site sélectionnée

Quand je saisie des sources d'émission, cela les ajoute uniquement pour le site sélectionné. 

Sur la page de résultat j'ai les infos du bilan carbone par site et une colonne avec le total

## Infos de test

Comment bien tester ce ticket ?

## Stratégie technique

Quelle strat technique adopter pour ce ticket ?

**Comment by cmolle** [comment]
Dans la page saisie des résultats, j'ai l'impression que le selecteur ne fonctionne pas. Quand je change le site, cela ne change pas les sources d'émission que je vois.

**Comment by cmolle** [comment]
@desoindx c'est normal que dans l'export beges je n'ai rien sur cette étude ?

**Comment by desoindx** [comment]
quel étude ?

**Comment by cmolle** [comment]
Celle-ci par exemple https://bilancarbone.osc-fr1.scalingo.io/etudes/8e0a8e53-c4d0-436a-a202-be007aae3aa7/comptabilisation/resultats (désolée pour l'oubli du lien)

**Comment by cmolle** [comment]
Vu ensemble : c'est dû aux incertitudes qui ne sont pas rentées. Ticket créé pour gérer le cas uniformément entre l"export et les résultat + pour que ce soit plus clair pour l'utilisateur.
