### ISSUE TITLE
Amélioration de l'affichage des Facteurs d'émission

### ISSUE THREAD

**Issue by cmolle** [ABC-TransitionBasCarbone/bilan-carbone#168]
## Contexte
Modification du style du tableau des facteurs d'émission

## Tests d'acceptance
Modifier le tableau existant pour qu'il soit comme l'image ci-dessous 

![Image](https://github.com/user-attachments/assets/3dd76d00-9d0a-47f3-9e0b-782d84992143)

On a une liste de FE, quand on clique sur le facteur d'émission, on a plus d'information sur celui ci (toutes les informations qui ne sont pas affichées sur la ligne du FE. 
Dans source, mettre l'icone de la base empreinte ou une icone mui qui indique que c'est un FE perso (à trouver) 

Que pensez-vous de mettre les FEs archivés en grisé ? @GChabahABC (en l'absence de réponse de Gabriel, le dev décide si c'est une bonne idée ou pas) 

## Infos de test

Comment bien tester ce ticket ?

## Stratégie technique

Quelle strat technique adopter pour ce ticket ?

**Comment by GChabahABC** [comment]
Hello @cmolle @desoindx, est-ce qu'on pourrait pas reprendre l'idée de la Base Empreinte où ils les mettent comme ça, avec une icône check quand c'est valide (on peut se contenter de mettre "valide" sans distinguer spécifique et générique pour l'instant), et une autre icône (livre ou autre) pour "archivé" ? On peut mettre ces logos dans la colonne source à côté du logo des bases qu'on intègre, et afficher "archivé" "valide" quand l'utilisateur hover sur l'icône.

Exemple de la base empreinte : 

![image](https://github.com/user-attachments/assets/cc855708-62e7-4c7e-a6aa-09dce3b995cb)

@cmolle Du coup il faut sûrement préciser dans ce ticket ou dans un qui fait le lien comment on affiche les FE archivés via les filtres ? Enfin faire un ticket "affichage FE archivés" du coup ^^
