### ISSUE TITLE
Page saisie des données, l'utilisateur doit pouvoir supprimer une source d'émission

### ISSUE THREAD

**Issue by GChabahABC** [ABC-TransitionBasCarbone/bilan-carbone#179]
## Contexte

Pour l'instant, il est possible d'ajouter des sources d'émission, mais pas d'en supprimer. 

## Tests d'acceptance

Les utilisateurs ayant les droits d'édition et de validation (les mêmes que pour ajouter une source) doivent pouvoir supprimer les sources d'émission en cas de besoin, via un bouton "Supprimer" (icône poubelle) situé à côté du bouton "Crayon" servant à éditer. 
Avant la suppression, une fenêtre de confirmation s'affiche dans le cas où des données **autre que le libellé** ont déjà été renseignées (contributeur, FE, donnée d'activité, incertitudes, etc). Idée de message : "Vous allez supprimer cette source d'émission. Toutes les données renseignées seront définitivement perdues, et les éventuels contributeurs n'auront plus accès à cette source d'émission. Souhaitez-vous poursuivre ?"  

---- à garder en tête pour la V2
Il faut également gérer le cas particulier des contributions, dans le cas où un contributeur a déjà été affecté à la source d'émission qui est supprimée, il faudrait idéalement qu'à sa connexion suivant il soit notifié des suppressions (il n'a plus à contribuer, qu'il n'aille pas chercher des données pour rien). La gestion de ce cas particulier peut venir dans une V2 ! 

## Infos de test

Vérifier qu'en tant que chaque type d'utilisateur, on peut bien supprimer les sources d'émissions renseignées, et qu'un message de confirmation s'affiche bien si et seulement si des informations autres que le libellé ont été renseignées

## Stratégie technique

Quelle strat technique adopter pour ce ticket ?

**Comment by cmolle** [comment]
@desoindx en tant que lecteur dans une étude, je pense que le bouton devrait être désactivé. Ici c'est uniquement le back qui bloque (mais sans message d'erreur affiché à l'utilisateur qui a l'impression qu'il ne se passe rien)

Aussi, il faudrait avoir un petit effet visuel sur la popup quand la personne clique sur oui en attendant la suppression effective et le retour de l'api. Au choix cela pourrait être que la désactivation des boutons ou desactivation + loading sur le bouton oui (à la place du texte)

J'en profite de ce retour, que penses-tu de mettre uniquement l'icone poubelle plutôt qu'un bouton avec le texte "supprimer cette source d'émission" ? Je trouve le bouton un peu gros du coup il retient l'attention dès qu'on ouvre une ligne, je trouve ca un peu dommage. Je te laisse voir si du coup en bas ca reste une bonne position ou si il faut le mettre ailleurs (tout en restant dans la section ouverte au clic)
