### ISSUE TITLE
ETQ contributeur, je recois un mail avec des infos sur le BC+

### ISSUE THREAD

**Issue by cmolle** [ABC-TransitionBasCarbone/bilan-carbone#188]
## Contexte
On envoie des mails aux contributeurs ajoutés dans une étude. Il faudrait qu'on leur donne des informations pour qu'ils sachent pourquoi ils recoivent ce mail et ce qu'ils doivent faire. On a deux cas : 
- La personne connait le BC+ et a un compte 
- La personne n'a pas de compte BC+

## Tests d'acceptance

Mail à envoyer

1er cas : personne qui a un compte BC+ 
![Image](https://github.com/user-attachments/assets/74616c29-d294-4e39-8c07-228d6a4f0ba9)

2ème cas : personne qui n'a pas de compte BC+
![Image](https://github.com/user-attachments/assets/f4305359-c1f9-4c36-9a89-23371096f570)

## Stratégie technique

Quelle strat technique adopter pour ce ticket ?

**Comment by desoindx** [comment]
En attente des FE manquant (Papier Moyenne et intercité 2019)

**Comment by cmolle** [comment]
@desoindx il faudrait enlever le "bienvenue sur le bc+ !" si la personne a déjà un compte. 

Aussi, est-ce que c'est voulu l'ajout de saut de ligne par rapport au modèle que j'avais fait ? 
![Image](https://github.com/user-attachments/assets/32d3c998-e798-4608-ae2e-443af4916471)
