### ISSUE TITLE
Incertitudes, il faut convertir les % de la Base Empreinte en qualités quand elles sont manquantes

### ISSUE THREAD

**Issue by GChabahABC** [ABC-TransitionBasCarbone/bilan-carbone#193]
## Contexte

Les calculs d'incertitudes s'effectuent grâce à cinq notes qualitatives attribuées à cinq caractéristiques (Représentativité Tech/Géo/Temp, Complétude, Fiabilité). Certains FE issus de la Base Empreinte n'ont pas ces données, en revanche ils ont toujours un % d'incertitude associé. Il faut donc convertir ce % en notes qualitatives de manière arbitraire en attendant la refonte de la Base Empreinte. 

## Tests d'acceptance

Il est arbitrairement décidé que la même note sera attribué à toutes les caractéristiques dans ce cas de figure. De même, la note associé à la caractéristique "Fiabilité" sera toujours "Très bonne", car les FE sont issus de la Base Empreinte. Soit X le % d'incertitude du FE :

Si 5<=X<20% : On associe la note "Bonne" aux quatre caractéristiques, et "Très bonne" à la fiabilité
Si 20<=X<45% : On associe la note "Moyenne" aux quatre caractéristiques, et "Très bonne" à la fiabilité
Si 45<=X<75% : On associe la note "Mauvaise" aux quatre caractéristiques, et "Très bonne" à la fiabilité
X=>75% : On associe la note "Très mauvaise" aux quatre caractéristiques, et "Très bonne" à la fiabilité

## Infos de test

Vérifier arbitrairement que les règles sont bien respectées sur des FE attribués à chaque poste/sous-poste.

## Stratégie technique

Quelle strat technique adopter pour ce ticket ?

**Comment by GChabahABC** [comment]
@fortinlouis Je pense que ce n'est pas bon ici car par exemple pour le FE "Cuivre, neuf", l'incertitude dans la Base Empreinte est de 50%, donc d'après ce ticket toutes les notes devraient être "Mauvaise", et seule la fiabilité "Très bonne", or, quand je vais dans la liste des FE sur le BC+, je vois Qualite : Très bonne (ce qui n'est pas normal) et Fiabilité : Très bonne (ce qui est normal). Cf capture. 

Donc soit : 
- C'est ce ticket qui pose problème et les caractéristiques ne sont pas bien affectés aux FE 
- C'est le calcul de la qualité du FE à partir des 5 caractéristiques (Représentativité technique, géo, temporelle, complétude, fiabilité) qui ne marche pas 
- C'est l'affichage dans la page "Facteur d'émission" qui n'affiche pas la bonne donnée

![Image](https://github.com/user-attachments/assets/e1041d42-166d-417f-8e0a-ca7b81ef77d6)

**Comment by fortinlouis** [comment]
Effectivement, les changements de la PR ont sauté https://github.com/ABC-TransitionBasCarbone/bilan-carbone/pull/209

**Comment by fortinlouis** [comment]
@GChabahABC Pour cet exemple en particulier, c'est l'import depuis l'API qui pose problème : On ne reçoit pas l'incertitude de la ligne "Cuivre"

C'est corrigé lors de l'import via le CSV qui lui fournit cette donnée

![image](https://github.com/user-attachments/assets/83add68f-65de-4e94-b63f-42cee2e741f0)
