### ISSUE TITLE
ETQ utilisateur, je peux valider les comptes de mes collègues qui ont été ajouté via le script

### ISSUE THREAD

**Issue by cmolle** [ABC-TransitionBasCarbone/bilan-carbone#197]
## Contexte
Une des façon de créer un compte utilisateur est via l'excel d'Almarena. Un script tourne régulièrement pour créer les comptes des nouveaux formés. 
- Si le formé est dans uen entreprise qui n'a pas déjà de compte : on créé une organisation 
- Si le formé est dans une entreprise qui a déjà un compte : on le rattache à cette organisation 

Cependant, pour des raisons de sécurité, il faut qu'on ajoute une validation manuelle de l'organisation. 

## Tests d'acceptance
Quand un utilisateur a été ajouté automatiquement par le script d'Almarena à mon organisation j'ai : 
- Une notification tout en haut de ma page d'accueil (doublé d'un mail pour tous les gestionnaires et administrateur)  (un bandeau qui indique "un utilisateur a été ajouté à votre organisation car il vient d'être formé à la méthode bilan carbone. Rendez-vous [dans la page de votre équipe](lien) pour valider son compte
- Sur la page équipe, je vois les personnes qui ont été ajouté via le script dans mon tableau d'équipe au début du tableau (pour l'instant écrire (à valider) à côté du nom, on verra pour faire un design différent après le point design). A droite de la ligne j'ai également deux boutons icones : un check vert et une croix rouge. Pour valider le compte je choisis un rôle et appuie sur le bouton check vert. Pour supprimer le compte, j'appuie sur le check rouge. 

Cas particulier : le compte de l'organisation n'existe pas encore et plusieurs personnes de cette organisation apparaissent dans l'excel (parce qu'ils ont suivis la formation en même temps ou parce qu'ils ont pris une licence par exemple). On créé le compte pour l'organisation et on ajoute la première personne que l'on voit dans l'excel. Les autres suivent le process habituel de validation. 

## Infos de test

Comment bien tester ce ticket ?

## Stratégie technique

Quelle strat technique adopter pour ce ticket ?

**Comment by cmolle** [comment]
Envoyer un mail aussi à tous les admin (et rh ?) de l'orga pour les prevenir qu'une personne a été ajouté

**Comment by cmolle** [comment]
Comment faire pour gérer les CGU ? A-t-on le droit de leur créer un compte automatiquement ? En parler avec Romain

**Comment by RomainCrevecoeur** [comment]
> Comment faire pour gérer les CGU ? A-t-on le droit de leur créer un compte automatiquement ? En parler avec Romain

@cmolle  Ah oui on en a un peu parlé à l'oral de ce sujet et on c'était dit que c'était ok je crois ?

**Comment by cmolle** [comment]
@desoindx peux-tu donner des indications sur comment tester ce ticket sur staging vu que la partie wordpress ne fonctionne pas encore ?
Aussi, j'ai pu refuser un utilisateur, qui n'apparait donc pas dans mon équipe, mais je me demande ce qu'il se passe pour cet utilisateur. Pourrais-tu du coup donner les mdp aussi des utilisateurs en question ?
