### ISSUE TITLE
Création des tables organisations

### ISSUE THREAD

**Issue by cmolle** [ABC-TransitionBasCarbone/bilan-carbone#20]
## Contexte
Chaque compte doit être relié à une organisation. Dans certains cas, il sera obligatoire d'avoir une adhésion à l'ABC afin de pouvoir accéder au BC+, mais dans d'autres, ce ne sera pas nécessaire (ex: associatif). Une organisation ne peut pas avoir plusieurs comptes, il faut donc que cette orga soit unique.
Il nous faut également une table (cela peut être la même ou non) pour gérer les organisatoins clientes des bureaux d'études. Elles ne sont pas uniques (plusieurs BE pourraient faire le BC d'une même entreprise) Une organisation dont on fait le BC peut avoir plusieurs entités afin de pouvoir faire le BC par entité de l'orga (toutes ces entités doivent être relié à une orga mère)

## Tests d'acceptance 
Avoir en bdd une table organisation avec les informations suivantes : 
- Nom
- Licence d'utilisation du BC+ (si organisation de compte)
- Adresse complète
- Timestamps
- Type (cf BC+ actuel pour les types à ajouter) 
- Adresse complète
- Données financières (début/fin, type, valeur, unité, monnaie)
- Nombre d'ETP par période (début/fin, quantité)
- Noms des produits et services

Vu ensemble pendant le point : on garde une même table pour les organisation de compte et les organisations d'étude. Il n'y a donc pas unicité sur les organisations. La différence entre les deux types d'organisation sera fait suivant si les champs remplis par le wordpress le son ou pas (ex : peut être un id, la licence ..?) 

## Infos de test
Pas de test

**Comment by GChabahABC** [comment]
@cmolle On peut ignorer cette partie, seuls les produits et services de cet onglet sont utiles > Je MaJ dans les tickets associés pour clarifier.

**Comment by cmolle** [comment]
Fait dans d'autres tickets
