### ISSUE TITLE
Attacher le CA et le nombre d'employé aux études et aux entités plutôt que directement aux entités

### ISSUE THREAD

**Issue by cmolle** [ABC-TransitionBasCarbone/bilan-carbone#206]
## Contexte
Le CA et le nombre d'employé d'une entité permettent de visualiser les résultats du bilan carbone par rapport à ces deux données.
Il faut donc que le CA et le nombre d'employés puissent être relié à la période de l'étude et non uniquement à une entité. 

## Tests d'acceptance
Dans la page de périmètre, donner la possibilité de définir et de modifier le CA et le nombre d'employés de chaque entité. 

Ailleurs dans le BC+ ces informations en sont jamais affichées. 

## Infos de test

Comment bien tester ce ticket ?

## Stratégie technique

Quelle strat technique adopter pour ce ticket ?

**Comment by cmolle** [comment]
@desoindx est-ce que ce ticket est bien déployé ? 
- Je peux encore modifier le CA et les ETP sur la page de modification d'une organisation alors que ce n'est plus pertinent de l'avoir ici 
- Je peux bien modifier le CA et les ETP à la création de l'étude mais je ne peux pas le modifier sur la page de périmètre

**Comment by desoindx** [comment]
Vu ensemble. On concerve le premier point (plus pratique à l'utilisation) et le second point sera traité dans le ticket #265
