### ISSUE TITLE
Rendre des champs obligatoires pour validation de la source d'émission + taux de complétion à afficher

### ISSUE THREAD

**Issue by GChabahABC** [ABC-TransitionBasCarbone/bilan-carbone#221]
## Contexte

On voudrait afficher pour une source d'émission comme statut : "En attente - 60%" sur la ligne résumé (ou "En attente, 60%"). Pour cela il faut définir des champs obligatoires à compléter sur une source d'émission pour pouvoir ensuite la passer en "Validée" (actuellement on peut valider avec aucune info).  Le pourcentage correspond donc au nombre de chmps obligatoire remplis / le nombre de champs obligatoire total

Champs à rendre obligatoires : Nom, Caractérisation (si nécessaire i.e si la personne a demandé des exports), FE, DA, type DA, soit 5 champs (4 si pas de carac).

## Tests d'acceptance

[ ] Quand je remplis la source d'émission j'ai des champs obligatoire (avoir une étoile à côté du nom) 
[ ] J'ai un pourcentage qui m'indique mon taux de complétion de ces champs obligatoires 

## Infos de test

Comment bien tester ce ticket ?

## Stratégie technique

Quelle strat technique adopter pour ce ticket ?

**Comment by GChabahABC** [comment]
Info supplémentaire, pour garder trace ici en plus de sur Slack : Autre truc important, par exemple dans le cas des Immos où on rajoute un champ "amortissement", dans l'idéal il faudrait que ce soit considéré comme obligatoire, je sais pas si ça aide de le savoir maintenant (après ça peut-être V2 ou plus ça)

**Comment by desoindx** [comment]
Compliqué le coté caracterisation obligatoire si jamais la personne a demandé des exports vu que c'est decorelle.

Qu'est ce qui se passe si la personne n'en demande pas, valide une source d'emission sans, puis en demande un ?

**Comment by cmolle** [comment]
@desoindx j'ai l'impression que la caractérisation ne compte plus dans les champs obligatoires (ne fait pas bouger le pourcentage et le validée s'affiche même si je ne l'ai pas rempli) pourtant il a bien l'étoile qui indique que c'est obligatoire. est-ce que c'est normal ?

**Comment by desoindx** [comment]
> [@desoindx](https://github.com/desoindx) j'ai l'impression que la caractérisation ne compte plus dans les champs obligatoires (ne fait pas bouger le pourcentage et le validée s'affiche même si je ne l'ai pas rempli) pourtant il a bien l'étoile qui indique que c'est obligatoire. est-ce que c'est normal ?

tu as mis un export beges ?

**Comment by cmolle** [comment]
@desoindx j'ai plus les étoiles sur caractérisation (j'ai bien sélectionné l'export beges) et type 
![Image](https://github.com/user-attachments/assets/fd727d07-061c-42d6-a7c8-0ba3d4e2aac0)

**Comment by desoindx** [comment]
effectivement ! Il manque un use case => je corrige
