### ISSUE TITLE
[BUG] Sur l'infographie des postes, pas d'accès au poste Fret

### ISSUE THREAD

**Issue by GChabahABC** [ABC-TransitionBasCarbone/bilan-carbone#222]
**Description du bug**

Lorsque je vais sur l'infographie des postes, (Compta > Saisie), cliquer sur les trois boites dédiées au Fret (entrant, interne, sortant qui sont les sous-postes) ne fait rien. 

**Etapes pour reproduire le bug**

Se rendre sur ladite page et cliquer sur Fret 

N.B : J'ai l'impression que ça remarche (même étude), mais que Fret est plus lent à s'ouvrir que le reste et fait planter le site de temps en temps - Peut-être que ce n'est pas spécifique au Fret du coup.

**Comportement attendu**

Normalement, ces clics sont censés renvoyer vers la page dédiée au poste "Fret" avec trois sous-postes : "Entrant, interne, sortant"

**Autres infos**

**Comment by cmolle** [comment]
@GChabahABC je n'arrive pas à reproduire le bug par contre c'est vrai que parfois je trouve que ca prend du temps pour accéder à la nouvelle page. Il faudrait peut être creuser de pourquoi ca prend autant de temps et si il y a un risque que ca arrive en prod 🤔

**Comment by desoindx** [comment]
Ca fonctionne tres bien chez moi aussi à retester maintenant qu'on a un serveur bien dimensionné

**Comment by GChabahABC** [comment]
Ok aussi de mon côté, c'était probablement ça !
