### ISSUE TITLE
[BUG] Désélection du FE

### ISSUE THREAD

**Issue by GChabahABC** [ABC-TransitionBasCarbone/bilan-carbone#224]
**Description du bug**

Lorsque je rentre dans une étude et que je choisit un FE pour une source d'émission, celui-ci se sélectionne et le calcul des émissions se fait bien. Lorsque je retourne à l'accueil de l'étude via le fil d'ariane, puis que je reviens sur la page où j'ai sélectionné le FE, celui-ci n'est plus sélectionné. Le résultat du calcul reste, mais le champ FE est vierge.

![Image](https://github.com/user-attachments/assets/8009614a-66ba-46b0-9e30-cd23dbee8cd9)

**Etapes pour reproduire le bug**

Se rendre dans "Intrants - biens et matières" > "Métaux plastiques verre" sur l'étude en capture, créer une source d'émission "Acier", ajouter le FE de l'acier neuf et 1000 tonnes comme donnée d'activité. Ensuite retourner au menu de l'étude via le fil d'ariane, puis retourner dans la saisie via le menu à gauche, dans Intrants - biens et matières : le FE a disparu.

**Comportement attendu**

Le FE doit rester enregistré et s'afficher à la fois lorsque la source d'émission est déroulée et lorsqu'elle est enroulée, sur le résumé.

**Autres infos**

**Comment by desoindx** [comment]
En attente de reproduction

**Comment by GChabahABC** [comment]
Ok, finalement c'est juste un temps de chargement un peu plus long, le FE se ré-affiche bien au bout d'un temps variable - Juste penser a bien check avant sortie que le temps est pas trop long. PI @cmolle
