### ISSUE TITLE
Création des tables de référentiels

### ISSUE THREAD

**Issue by cmolle** [ABC-TransitionBasCarbone/bilan-carbone#24]
## Contexte
Une fois la comptabilité carbone finalisé, les utilisateurs souhaitent pouvoir exporter leurs données sous différents formats. Il faut que l'on puisse stocker les référentiels que l'on permet d'avoir à l'utilisateur pour qu'il puisse les sélectionner. ON en a besoin en base de données car il va y avoir toute la partie ventilation où il y aura forcément des informations en bdd je pense. 

## Tests d'acceptance 
Créer la ou les tables nécessaire pour stocker les informations des référentiels et mode de controle. Informations à stocker : 
- Nom du référentiel : Bilan GES Règlementaire, GHG Protocol (+ les autres déjà présents sur le bc+ autre que les deux précédents qui sont du renommage)
- Mode de controle : plusieurs possibles (financier, opérationnel, part du capital)

**Comment by desoindx** [comment]
Done with #10 

Les noms de referentiel sont pour l'instant en enum, a voir quand les infos de validations seront la pour voir ou et comment on les stocks
