### ISSUE TITLE
Cas particuliers de calcul - immobilisation

### ISSUE THREAD

**Issue by GChabahABC** [ABC-TransitionBasCarbone/bilan-carbone#252]
## Contexte

Pour certains sous-postes, des cas particuliers se présentent au sein du calcul. 
Ceci est pour l'instant identifié sur deux cas : 
- Les immobilisations, pour lesquelles une durée d'amortissement doit être définie, et le résultat à inscrire au sein du Bilan Carbone® et du BEGES est : DA*FE/Durée d'amortissement
- Les changements d'affectation des sols (CAS), pour lesquels certains FE sont en ha.an (vs d'autres en ha seulement). Les utilisateurs sachant rarement utiliser ces ha.an, il est préférable que deux boites apparaissent au sein du BC+ pour ces FE, une boite "durée" et une boite "hectares. La boite durée serait ici précomplétée par "20" (car les FE Base Empreinte® sont de base prévus pour des équilibres sur les sols qui se mettent en place au bout de 20 ans), mais resterait modifiable par les utilisateurs si ceux-ci ont des données plus précises (études sur les sols en question par ex). 

D'autres cas particuliers pourront se présenter dans le futur, ainsi il est préférable de trouver une façon globale de gérer ces cas. Je propose que les champs s'affichent lorsque l'utilisateur sélectionne un FE sur lequel un cas particulier se présente. 

Pour les immobilisations et afin de changer le moins possible la modélisation, est-ce qu'on ne pourrait pas dire que le champ actuel "Donnée d'activité" du BC+ est remplit par le nombre de m^2/durée d'amortissement ? 

## Tests d'acceptance

Lorsque je sélectionne un FE au sein du poste "Immobilisations", je peux compléter deux champs pour la donnée d'activité : le nombre de m^2 ou d'unité d'oeuvre (selon le FE), et la durée d'amortissement. 
J'ai ensuite au sein des mes résultats Bilan Carbone® et BEGES : DA*FE/durée d'amortissement. 

Attention, pour le GHG Protocol, il y aura un cas particulier à anticiper : le ghg n'amortit pas les biens, il prend en compte la totalité des émissions l'année de construction/achat. Il faudra donc, selon les équipements, un champ supplémentaire demandant : "L'équipement à t'il été acheté cette année"/"Le bien a t'il été construit cette année" > Si la réponse est oui, toute les émissions sont prises en compte, sinon, aucune émission n'est prise en compte. 

## Infos de test

Comment bien tester ce ticket ?

**Comment by cmolle** [comment]
@GChabahABC est-ce que je peux découper ce ticket en deux pour gérer d'un côté l'amortissement (qui est prio) et de l'autre le CAS (que l'on peut faire dans un second temps). Je garderais les deux dans le contexte pour que la solution choisie pour l'amortissement soit bien possible à utiliser pour d'autre cas et notamment pour le CAS

**Comment by GChabahABC** [comment]
@cmolle Oui, je l'avais mis pour contexte vu que Xavier mentionnait le fait de devoir être au courant des changements de ce style au maximum en même temps pour faire un truc propre.
