### ISSUE TITLE
Total avec et sans le sous-poste dépendance

### ISSUE THREAD

**Issue by GChabahABC** [ABC-TransitionBasCarbone/bilan-carbone#253]
## Contexte

La méthode Bilan Carbone® préconise de restituer le résultat final avec et sans le sous-poste Dépendance (car ce sous-poste peut écraser le reste du bilan, par exemple pour un fabriquant de pièces de moteurs automobiles, la dépendance peut être l'ensemble des émissions liées au trafic routier induit - Cela sert à bien prendre conscience de sa dépendance à ce secteur d'activité très carboné). Il faut donc pouvoir le faire au sein du BC+. 

## Tests d'acceptance

Sur la page résultat et sur le sous poste dépendance, j'ai un sélecteur qui me permet de choisir si j'affiche le Bilan Carbone® avec ou sans la dépendance. 

## Infos de test

Comment bien tester ce ticket ?

## Stratégie technique

Quelle strat technique adopter pour ce ticket ?

**Comment by cmolle** [comment]
@GChabahABC il s'agit bien du sous poste utilisation EN dépendance ? (et non le poste utilisation et dépendance en entier ?)

**Comment by GChabahABC** [comment]
@cmolle Oui, le sous-poste, pas le poste en entier ! le but c'est de garder l'utilisation en responsabilité et juste d'enlever la dépendance.

**Comment by cmolle** [comment]
@GChabahABC Est-ce qu'on fait le changement que pour la page résultat ou aussi sur les graphiques ?

**Comment by GChabahABC** [comment]
Pour tous, je pense que c'est plus simple d'avoir la même chose partout pour le coup !
