### ISSUE TITLE
Base de FE Légifrance - Attribution postes/sous-postes

### ISSUE THREAD

**Issue by GChabahABC** [ABC-TransitionBasCarbone/bilan-carbone#254]
## Contexte

Une fois les FE Légifrance importés, ceux-ci devront être mis à disposition dans les sous-postes "Réseaux de chaleur et de vapeur" et "Réseaux de froid".

## Tests d'acceptance

Lorsque je me rend dans le sous-poste "Réseaux de chaleur de de vapeur", j'ai bien accès aux FE Légifrance.
Lorsque je me rend dans le sous-poste "Réseaux de froid", j'ai bien accès aux FE Légifrance.

## Infos de test

Comment bien tester ce ticket ?

## Stratégie technique

Quelle strat technique adopter pour ce ticket ?

**Comment by GChabahABC** [comment]
@cmolle Je ne sais pas trop quelle tête a l'excel d'import là-dessus - Est-ce que tu peux détailler comment identifier ceux qui vont dans chaleur/vapeur et ceux qui vont dans froid ?

**Comment by cmolle** [comment]
Vu ensemble, il y a deux excels différents un pour les réseaux de froid et un autre pour les réseaux de chaleur

**Comment by fortinlouis** [comment]
[reseaux_de_froid_formatte_ademe.xlsx](https://github.com/user-attachments/files/18195880/reseaux_de_froid_formatte_ademe.xlsx)
[Reseaux_de_chaleur_formatte_ademe.xlsx](https://github.com/user-attachments/files/18195881/Reseaux_de_chaleur_formatte_ademe.xlsx)

**Comment by cmolle** [comment]
idem que pour negaoctet

**Comment by cmolle** [comment]
N'est pas encore géré l'utilisation de ces FEs dans les études, en attente d'un nouveau ticket car il y a des complexités techniques
