### ISSUE TITLE
Base de FE Négaoctet - Attribution postes/sous-postes

### ISSUE THREAD

**Issue by GChabahABC** [ABC-TransitionBasCarbone/bilan-carbone#255]
## Contexte

Une fois la portion de la base de FE Négaoctet accessible via la Base Empreinte® importée, il faut ajouter les différents FE aux sous-postes concernés. 
Tous ces FE iront dans "Intrants - services" > "Usages Numériques".

## Tests d'acceptance

Lorsque je me rends dans "Usages Numériques", j'ai bien accès aux FE Négaoctet.

## Infos de test

Comment bien tester ce ticket ?

## Stratégie technique

Quelle strat technique adopter pour ce ticket ?

**Comment by cmolle** [comment]
Vu ensemble et Gabriel a mis à jour le ticket, tout va bien dans usages numériques

**Comment by fortinlouis** [comment]
[NegaOctet - v2.xlsx](https://github.com/user-attachments/files/18195878/NegaOctet.-.v2.xlsx)

**Comment by fortinlouis** [comment]
Exécution du script d'import : 
- `npx ts-node src/scripts/legifrance/getEmissionFactors.ts -n 1 -f reseaux_froid.csv -r froid`
- `npx ts-node src/scripts/legifrance/getEmissionFactors.ts -n 1 -f reseaux_chaud.csv -r chaud`

**Comment by cmolle** [comment]
Erreur lorsque l'on va sur la page des FE, il manque une clé de traduction
![Image](https://github.com/user-attachments/assets/ac0334f3-ec10-415f-bf81-288d199fa003)

**Comment by cmolle** [comment]
N'est pas encore géré l'utilisation de ces FEs dans les études, en attente d'un nouveau ticket car il y a des complexités techniques
