### ISSUE TITLE
Création de(s) base(s) de données de facteurs d'émission

### ISSUE THREAD

**Issue by GChabahABC** [ABC-TransitionBasCarbone/bilan-carbone#29]
## Contexte

Pour calculer les émissions associées à une source d'émission, les utilisateurs associent une donnée d'activité (par exemple un nombre de tonnes d'acier neuf acheté à un fournisseur) à un facteur d'émission (par exemple celui de l'acier neuf, qui donne le nombre de CO2e associés à l'achat d'une tonne d'acier neuf). En multipliant la donnée d'activité (DA) par le facteur d'émission (FE), les utilisateurs obtiennent les émissions associées. 

Il existe de nombreux FE, qui doivent être mis à disposition au sein de l'outil. Plusieurs bases de données différentes sont sources de ces facteurs d'émission (ex : https://base-empreinte.ademe.fr/, https://agribalyse.ademe.fr/, https://www.inies.fr/, ...). Ces bases de données évoluent dans le temps, avec l'ajout de nouveaux FE, la modification de FE existants, etc.

L'outil doit permettre de sélectionner des FE provenant : 
- Dans un premier temps, de la Base Carbone® de l'ADEME uniquement (La Base Empreinte® est la fusion des bases Carbone® et Impacts®, qui donne accès aux données de ces deux bases : https://base-empreinte.ademe.fr/)
- Dans un second temps, d'autres base de données jugées utiles

La Base Empreinte® mets à disposition un fichier .csv avec les données, mais une API existe également pour la base Carbone®. Vous pouvez trouver le .csv sur la base, dans "Données > Télécharger les données", et l'API ici : https://api.gouv.fr/les-api/api_base_carbone. 

Il faut a priori que différentes versions de la base de FE coexistent, car si la Base Empreinte fait une mise à jour de ses FE, il ne faut pas que tous les Bilans Carbone® existants sur le BC+ voient leurs valeurs modifiées : cette modification des valeurs pour les mettre à jour vers telle ou telle année des données (exemple, j'ai un bilan fait en 2015, je souhaite le mettre à jour avec les données 2020 pour le comparer à mon bilan 2020) doit être demandée par l'utilisateur. 

Pour la base Empreinte/Carbone, les données qui seront utilisées sont a priori : 
- Colonne A (certains FE sont décomposés en plusieurs parties, dans le .csv les "éléments" sont la somme des "postes". L'utilisateur du BC+ doit voir seulement l'élément, mais la décomposition par poste est importante pour affecter les émissions dans les différents exports)
- Colonne B (l'identifiant unique sera certainement utile)
- Colonne E (Seuls les FE valides seront proposés aux utilisateurs dans un premier temps, mais si demande utilisateurs il est possible que le BC+ doive aussi proposer certains archivés)
- Colonnes F à N & P à R (Libellés dans plusieurs langues, décomposés en F à N et complets de P à R je crois)
- Colonnes S à U (unités dans plusieurs langues)
- Colonne Z 
- Colonnes AA à AD
- Colonne AH puis AL à AO (Incertitudes)
- Colonnes AR à AX
- Colonnes AY à BC puis BN et BO (valeurs)

L'outil doit permettre aux utilisateurs d'ajouter leurs propres FE au sein de l'outil (par exemple dans le cas où une organisation aurait effectué une ACV sur un de ses propres produits). Les FE ajoutés par des utilisateurs doivent : 
- Être visibles par les autres comptes utilisateurs de la même organisation
- Ne pas être visible ni par les autres comptes organisations et leurs utilisateurs, ni par nous 

## Tests d'acceptance 
A faire dans ce ticket : Créer un script qui permet d'importer tous les FEs de l'Ademe dans l'outil

## Infos de test

[...]

## Stratégie technique 

[...]

**Comment by cmolle** [comment]
@GChabahABC, quelques questions sur ce ticket : 
- les informations qui sont indiqués comme données sources dans la base empreinte, on les importe en tant que facteur d'émission dans le bc+ ? 
- Pour les colonnes P à R ce sont des tags qu'on n'utilise pas aujourd'hui dans le bc+, tu voudrais qu'on les affiche à l'utilisateur ? (je me demande remarque si ca pourrait pas être utile pour de la recherche sur mot clés 🤔) 
- Tu ne veux pas qu'on affiche les contributeurs ? (colonne V et W) c'est peut être redondant avec la source ? 
- Pas besoin des dates de création/validité ? 
- On ne garde pas les colonnes de décomposition de "autres gaz" ni la valeur totale non décomposée ? côté tech c'est celle qu'on utilise dans le bc + actuelle pour calculer les émissions. 

ON peut s'appeler si besoin

**Comment by GChabahABC** [comment]
@cmolle 
- Oui, ce sont juste les PRG100, on les utilise pour convertir les kg de méthane et autres gaz en kgCO2e, donc quand des FE ont différents gaz, c'est ça qu'on utilise pour tout convertir et donner une valeur globale en CO2e, mais ça c'est déjà fait au sein de la base empreinte colonne AY (à voir s'il vaut mieux recalculer nous à partir de toutes les valeurs pour tous les GES ou direct utiliser la colonne AY). Par contre ça devient des FE quand on a une entreprise qui émet du méthane (par exemple GRDF qui a des fuites dans son réseau) : j'ai xx kg de méthane émis, je multiplie par le PRG qui du coup est comme un FE
- Colonnes P à R j'ai l'impression que c'est l'agrégation des colonnes F à N non ? J'ai mis au cas où !
- Je pense que c'est un peu redondant oui, si ça coute rien de les mettre dans la BDD au cas où un jour on veut les utiliser mettons les, là j'ai essayé de mettre que les colonnes qui allaient très certainement être utiles, mais peut-être que c'est mieux de tout importer et après on voit ce qu'on utilise 
- Pas besoin, on triera que selon le tag "Valide générique" "Archivé" etc ! 
- Euh si, je MaJ, c'est AY à BC et BN, BO. Normalement BN c'est déjà les autres GES, je crois pas que BD à BM servent ?

**Comment by cmolle** [comment]
@GChabahABC Quand je filtre sur les colonnes BD à BM il y a bien certaines informations (pour les gaz divers et sf4). est-ce qu'on conserve du coup ?

**Comment by cmolle** [comment]
Vu ensemble : on somme tout dans autre GES

**Comment by desoindx** [comment]
RAF => [Historisation](https://github.com/orgs/ABC-TransitionBasCarbone/projects/3/views/1?pane=issue&itemId=83300023&issue=ABC-TransitionBasCarbone%7Cbilan-carbone%7C41)
