### ISSUE TITLE
En tant qu'utilisateur je peux me connecter

### ISSUE THREAD

**Issue by cmolle** [ABC-TransitionBasCarbone/bilan-carbone#33]
## Contexte
Pour l'instant, on n'a pas accès au  wordpress comme on veut, on est en attente de notre prestataire sur ce sujet. En attendant, on ne gère pas toute la partie récupération des comptes depuis le wordpress et vérification des informations. 

## Tests d'acceptance 
Quand je rentre mon mail sur le BC+, cela me créé un compte avec une organisation fictive et m'envoie un mail avec un magic link pour définir mon mot de passe. 
Je peux alors me connecter et ajouter d'autres comptes pour mon entreprise. 

## Strat tech 
On utilise OVH pour envoyer les mails. Pour l'instant définir des textes bâteaux d'inialisation de mot de passe/création de compte et on verra plus tard pour faire des mails un peu plus quali.

**Comment by desoindx** [comment]
RAF : Connecter OVH en prod
