### ISSUE TITLE
Création de la page équipe projet - utilisateur externe à l'orga déjà existant

### ISSUE THREAD

**Issue by cmolle** [ABC-TransitionBasCarbone/bilan-carbone#34]
Nécessite que les tables de rôles et droits soient déjà faites #19  et #47 
## Contexte

La page "Équipe Projet" sert à définir les droits des utilisateurs plus finement que la page "Gestion de l'équipe", en pouvant définir des droits spécifiques au niveau de l'étude. Elle permet également d'ajouter des utilisateurs qui ne sont pas membre de l'organisation à une étude spécifique. Cette fonctionnalité est utilisée pour inviter des clients, partenaires, etc, à prendre part à une étude spécifique. L'ajout pourrait se passer comme suit : 
- L'utilisateur peut rajouter quelqu'un de son organisation via une liste déroulante
- L'utilisateur peut rajouter quelqu'un en tapant son mail et là :
1. Si la personne est déjà au sein de l'organisation (i.e elle aurait pu être ajoutée via la liste déroulante) > Elle est ajoutée comme si c'était fait via la liste
2. Si la personne est utilisatrice du BC+ mais au sein d'une autre organisation, un pop-up s'ouvre avec un message type "La personne que vous souhaitez ajouter est utilisatrice du BC+ au sein d'une autre organisation que la votre. Souhaitez-vous vraiment l'ajouter à cette étude ?"
3. Si la personne est externe au BC+, il faut qu'un message s'affiche disant "Cette personne n'est pas utilisatrice du BC+, vous ne pourrez donc lui donner un accès à l'étude qu'avec les droits de consultation ou de contribution." >Et du coup là plus que ces deux droits de sélectionnables.

Ce ticket est dédié uniquement à la gestion des utilisateurs externes à l'organisation mais ayant un compte au sein du BC+ (rattaché à une autre organisation), **c'est-à-dire au second bullet point ci-dessus, numéros 1. & 2.** Pour une vision plus globale sur les droits, voir cette image : ![Image](https://github.com/user-attachments/assets/fdac2c7a-d88e-429d-b117-d045b4a66b16)

## Tests d'acceptance
Ici on fait une V1 sans gérer le sujet de sécurité. Celui-ci sera à gérer dans un prochain ticket. 

Pour ajouter une personne au sein de l'équipe projet : 
- Dans la page "Ajouter une personne" dans un projet : si la personne rentre une personne externe de l'organisation, celle-ci ne peut lui ajouter que les rôles suivants : 
     - Si la personne a sa formation et licence à jour : tous les roles 
     - Sinon uniquement le role lecteur ou contributeur
- A la validation du formulaire, une popup s'affiche indiquant "vous inviter une personne hors de votre organisation, en êtes-vous sur ? Un mail lui sera envoyé pour lui donner accès à l'étude". 

Les droits sont ensuite les mêmes que pour le ticket #35 

## Infos de test

Tester les différents types de droits et le bon fonctionnement comme évoqué dans le ticket #35, mais uniquement pour les utilisateurs externes à l'organisation mais ayant un compte au sein du BC+.

## Stratégie technique

[...]

**Comment by cmolle** [comment]
@GChabahABC je ne sais pas trop si on peut faire une différence entre quelqu'un qui a un compte pour une autre organisation et quelqu'un qui n'en a pas... ce sera affiché les mails qui ont un compte chez nous publiquement ce qui est un peu gênant d'un point de vue sécurité (c'est pour ca que quand tu fais mdp oublié sur un site ca te dit jamais si tu as vraiment un compte). 

Pourquoi est-ce qu'il y a une différence de droit possible entre quelqu'un qui a déjà un compte et quelqu'un qui n'en n'a pas ?

**Comment by cmolle** [comment]
Pour être sûre de bien comprendre on a les cas suivant : 
- Si un utilisateur ajoute un utilisateur externe mais qui a déjà un compte actif (i.e. il est adhérent à l'ABC ou a une licence active) : cela lui envoie un mail lui indiquant qu'il a été ajouté à une étude externe + lui envoie un lien + l'étude est accessible (il faudra peut être mettre une démarcation) sur sa page d'accueil. Il peut avoir les rôles validateurs, editeur ou lecteur sur l'étude 
- Si un utilisateur ajoute un utilisateur externe mais qui n'a pas de compte actif (pas de compte ou licence non à jour) : celui lui envoie un mail pour créer son compte le cas échéant ou juste lui indiquer qu'il a été ajouté à une étude externe. Il peut avoir uniquement le role éditeur ou lecteur ?

**Comment by cmolle** [comment]
Quand quelqu'un invite une personne externe : 
- si la personne a un compte avec une licence et une formation a jour il peut donner édition et validation 
- Sinon seulement lecteur/contributeur

A voir niveau sécurité comment on fait bien ca, mais une des possibilités est de forcément envoyer un mail pour ne pas pouvoir tester 1000 adresse mails sans que personne ne soit au courant

**Comment by GChabahABC** [comment]
@desoindx Hello, j'ai testé de m'ajouter deux fois au sein d'études avec le même compte (dans une étude A je m'ajoute, le site me remet bien en tant que lecteur au lieu de validateur), et à l'ajout dans l'étude B, j'ai eu la capture suivante, le site me retourne "Not authorized" au lieu de changer mes droits en tant que lecteur et de m'ajouter. Bug mineur, mais peut-être qu'il y a des soucis lorsqu'une personne est ajoutée à plusieurs endroits ? 

![Image](https://github.com/user-attachments/assets/685741fd-6a62-4425-b7fb-f3eea30d23d9)

**Comment by cmolle** [comment]
Pour ce ticket à voir si ce n'est pas fix par la PR en cours de Louis #237

**Comment by fortinlouis** [comment]
> Pour ce ticket à voir si ce n'est pas fix par la PR en cours de Louis #237

C'est oké pour moi, y compris sur la branche develop. À re-tester sur staging
