### ISSUE TITLE
[BUG] Erreur lors de la déconnexion

### ISSUE THREAD

**Issue by cmolle** [ABC-TransitionBasCarbone/bilan-carbone#38]
**Description du bug**
Erreur lors de la déconnexion. 

**Etapes pour reproduire le bug**
Se connecter sur le site, puis cliquer sur le bouton de déconnexion. De manière furtive, on voit une error pop à gauche. dans la console on a l'erreur suivante 
![Image](https://github.com/user-attachments/assets/0bcb1b0f-9a7c-47ac-a312-00bb3f78e741)

Le bug a aujourd'hui uniquement été vu sur firefox (sans extension)

**Comment by desoindx** [comment]
@cmolle tu as encore l'erreur ?

**Comment by cmolle** [comment]
Le bug n'est plus reproductile
