### ISSUE TITLE
Création de la table des facteurs d'émission

### ISSUE THREAD

**Issue by cmolle** [ABC-TransitionBasCarbone/bilan-carbone#40]
## Contexte
Nous avons besoin de conserver en bdd tous les facteurs d'émissions (FE) de l'Ademe ainsi que d'autres FE (provenant d'autres sources ou alors directement des utilisateurs)

## Tests d'acceptance
Avoir une table en bdd pour les FEs avec les champs suivants : 
- idImport (id du FE depuis la source) 
- ImportedFrom (possiblement null)
- Type (je suis pas sûre qu'on en ait besoin, vu que si l'élément n'a pas de type de poste alors c'est un élément sinon c'est un poste)
- Status
- titleFr (fusionner ici le nom de base et l'attribut, idem pour ceux en dessous)
- titleEn
- titleEs
- additionnalInfosFr (colonnes L à N)
- additionnalInfosEn
- additionnalInfosEs
- unitsFr
- unitsEn
- unitsEs
- tagsFr
- tagsEn
- tagsEs
- Source
- locationFr (fusion des colonnes localisation et sous loc fr)
- locationEn (à voir comment on fait la traduction de la localisation)
- locationEs 
- Incertitudes (colonne AH)
- TechnicalRepresentativeness (qualité Ter)
- GeographicRepresentativeness (qualité GR)
- TemporalRepresentativeness (qualité Tir)
- Completeness (qualité C)
- commentsFr
- commentsEn
- commentsEs
- decomposition (type de poste) - à voir si on trouve un meilleur nom (idem poru ceux en dessous)
- decompositionTitleFr
- decompositionTitleEn
- decompositionTitleEs
- totalCo2
- Co2F
- Ch4f
- Ch4b
- N2o
- otherGes (y sommer la colonne autre Ges + toutes les valeurs gaz supplémentaires
- Co2b

Voir l'excel accessible sur la base empreinte pour avoir plus d'informations sur les champs

**Comment by GChabahABC** [comment]
@desoindx 

Petit ajout : 
- Il faudra aussi un champ "Fiabilité" dans les incertitudes (Reliability en EN), qu'on ajoutera nous (normalement il apparaitra au sein de la Base Empreinte dans l'année, mais pour l'instant il n'existe pas) > Par défaut on mets "5" comme valeur pour ce champ quand les FE viennent de la Base Empreinte en attendant qu'ils les rajoutent

**Comment by desoindx** [comment]
RAF => Historisation
