### ISSUE TITLE
Gestion de l'historisation des facteurs d'émission

### ISSUE THREAD

**Issue by cmolle** [ABC-TransitionBasCarbone/bilan-carbone#41]
## Contexte
Les facteurs d'émission sont régulièrement mis à jour. Lorsqu'on les met à jour, il ne faut pas que les études soient mises à jour automatiquement. Parcontre il faut qu'ils puissent choisir de mettre à jour les FEs de leurs études finies ou en cours. Il faut donc que les anciens Fes soient dispos pour les anciennes études mais également pour celles en cours si l'utilisateur ne souhaitent pas d'utiliser la nouvelle version de la base. 

## Tests d'acceptance
Augmenter la table de FE ou ajouter des tables avec les infos nécessaire au comportement suivant : 
- Si la version des FE de l'étude ne correspond pas à la dernière version des FEs dispos en base de données alors on propose à l'utilisateur de mettre à jour les FE à l'ouverture de l'étude 
- S'il dit non rien ne se passe, 
- Sinon on met à jour son étude avec les nouveaux FE

## Infos de test

Comment bien tester ce ticket ?

## Stratégie technique
On a deux tables : 
- Une table version avec les colonnes : 
    - id
    - Nom
    - Date
    - Nom de fichier
-  Une table avec les FE : on fait une ligne par version qu'il y ait des changements ou non  
   - Différence par rapport à aujourd'hui, la colonne version Id 

- On rajoute l'id de version dans la table study. On verra plus tard comment gérer le fait d'avoir plusieurs sources quand on aura une vision plus clair de l'app et de l'historisation de FE

Lors de l'import : si le nom de fichier existe déjà, on ne créé pas l'import, sinon on fait l'import avec le nom donné en parametre. On revérifie si le nom existe déjà et si oui on ne fait pas l'import.

**Comment by fortinlouis** [comment]
**Proposition de stratégie n°1**
- Ajout d'une colonne "version" dans la table "emissions" pour gérer les mises à jour.
- Création d'une table "historic_emissions" copie de "emissions" avec une colonne "emission_id"

- Lors des MAJ des FE, on copie les lignes dans la table historique, puis on fait la MAJ.
- Lors de la récupération des études, on va chercher les valeurs dans la table emissions ou historic_emissions, basée sur l'id de l'emission et le numéro de version
- Lors de la création d'une étude, on se base uniquement sur la table emissions
- On nettoie la table historic_emissions dans un cron pour supprimer les lignes qui ne sont plus utilisées dans aucune étude.

Avantage : 
- On garde la table emissions la plus petite possible

**Comment by fortinlouis** [comment]
**Proposition de stratégie n°2**

- Ajout d'une colonne "version" dans la table "emissions".
- Ajout d'une colonne "active_version_id" dans la table "emissions".
- On garde la colonne "status" (valid, Archived) de la table "emissions" pour gérer les status

----

- Lors des MAJ des FE, on modifie la ligne pour lui donner le statut "Archived", on ajoute la nouvelle ligne puis on modifie "active_version_id" pour toutes les versions "archived".
- Lors de la récupération des études, on va chercher les valeurs dans la table emissions, basée sur l'id + numéro de version ou active_version_id + numéro de version
- Lors de la création d'une étude, on se base uniquement les lignes "valid" de la table emissions
- On nettoie la table emissions dans un cron pour supprimer les lignes "Archived" qui ne sont plus utilisées dans aucune étude.

Avantage : 
- Une seule table

Inconvénient : 
- Table plus complexe à gérer

**Comment by desoindx** [comment]
Plusieurs probleme : 
* Une mise à jour de la base empreinte ne veux pas dire une mise a jour de tout les facteurs. Du coup on optimise pas vraiment ca. Mais en meme temps est ce un probleme ? 
* Pas besoin de deuxieme table, une seule table avec un index fera tres bien le travail
* On peut pas vraiment changer le status en archived (c'est un status deja gerer pas la base empreinte)

le reste me plait bien

**Comment by fortinlouis** [comment]
Oké pour 1 seule table, dans ce cas, il faudrait savoir ce qu'il se passe quand la base est mise à jour :
- Nouvel import de 17000 lignes (mises à jour ou pas)
- Nouvel import de X lignes à mettre à jour
Si le statut "Archived" n'est pas de notre responsabilité, il faut, je pense, ajouter un statut "updated" pour signifier qu'il existe une valeur du FE plus récente et se donner la possibilité d'un nettoyage. Autrement on pourrait rapidement se retrouver avec une table ingérable

**Comment by desoindx** [comment]
Updated va pas etre suffisant.
je pensais plus a un systeme de date de validité ?

et je suis vraiment pas sur du coté ingérable... Même si on part du principes que tout les facteurs sont mis à jour (ce qui n'est pas le cas), avec 4 update max par an, dans 10 ans on a pas encore un million de ligne...

**Comment by fortinlouis** [comment]
La date de validité, je trouve cela bien pour pouvoir recréer une base à un instant T, mais est ce que c'est quelque chose que l'on souhaite vraiment faire ? Ou il y a des fonctionnalités que l'on souhaite implémenter qui m’échappent ?

Avec le statut "Updated" :
- Les études se basent sur l'id du facteur d'emission, donc que celui-ci soit valid ou updated ne change rien. On peut également proposer de mettre à jour en récupérant le FE valid (basé sur importedId)
- Lors de la récupération des FE, on ne garde que ceux qui sont valid, sans se soucier de la date.
- Lors de la MAJ de la base, pour chaque ligne créée, on va simplement changer le statut de celui qui a le même importedId et le statut valid, avant d'ajouter la ligne. De plus, le updatedAt fait office de validityEndDate sachant qu'une MAJ d'un FE signifie que la ligne n'est plus valide
- Même si je pense qu'il ne faut pas attendre le million de ligne pour faire un nettoyage, on pourra toujours se préoccuper de nettoyer la base quand on constatera des soucis de performances

Ça me parait le système le plus simple à implémenter sachant qu'il s'agit de n'ajouter qu'une valeur à l'enum. Sauf si, encore une fois, il me manque des fonctionnalités qui ne seraient pas couvertes ?

**Comment by desoindx** [comment]
tu peux updater un FE sans le rendre "updated" par exemple pour corriger une typo
