### ISSUE TITLE
ETQ utilisateur, j'ai accès à une page de facteur d'émission

### ISSUE THREAD

**Issue by cmolle** [ABC-TransitionBasCarbone/bilan-carbone#43]
## Contexte
Les utilisateurs veulent parfois pouvoir consulter les facteurs d'émissions disponibles sur l'outil sans forcément être dans une étude. De plus, il leur arrive d'avoir besoin de facteurs d'émissions spécifiques qui ne sont pas disponibles dans les bases de données que nous importons et il faut donc qu'ils aient un endroit pour les créer et les gérer. 

## Tests d'acceptance
En tant qu'utilisateur, quand je clique sur le bouton Facteur d'émission du bandeau de navigation je suis redirigé vers une page de facteurs d'émission avec : 
- un titre 
- un bouton ajouter (qui ne fait rien pour l'instant) 
- un tableau me listant les FEs accessibles dans ma bdd

![Image](https://github.com/user-attachments/assets/f0311c29-bb1e-4c66-b0ce-f9559df232ce)

Quelques informations sur le tableau : 
- Dans la partie qualité : on fait une moyenne des 5 critères de qualité, quand la personne passe sa souris sur la case, il a un tooltip avec le détail des 5 notes de qualité de ce FE
- Les trois icones sont :  
     - un bouton qui ouvrira une modale qui permettra de savoir où trouver ce FE (quelle catégorie > domaine... )
     - un bouton pour modifier le FE (uniquement sur les FEs créés par l'utilisateur ou ses collèges et si celui ci n'est pas utilisé dans des études)
     - un bouton pour supprimer le FE (idem)

## Stratégie technique

Pour bien choisir le type de tableau à utiliser voici les contraintes que nous avons : 
- il y a environ 17000 FE dans un import de la base empreinte, sachant que nous allons également devoir gérer une historisation et donc gérer plusieurs dizaine de facteurs d'émission sur cette page. 
- Nous allons vouloir filtrer sur plusieurs colonnes 
- Eventuellement, ca pourrait être cool que l'utilisateur puisse choisir les colonnes qu'il souhaite afficher. 
(J'avais vu le datagrid de mui qui avait l'air assez cool, mais du coup ca filtre en front, donc je me dis que c'est pas l'idéal dans notre cas)

Ce tableau va être réutilisé à plusieurs endroits (au moins également à l'endroit de la gestion de l'import des FEs)

**Comment by GChabahABC** [comment]
@desoindx 

Lors d'un ajout de FE par les utilisateurs, l'utilisateur doit obligatoirement renseigner : 
- Un libellé 
- Une unité
- La source
- Les cinq indicateurs sur les incertitudes (Représentativité Technique/Représentativité Géographique/Représentativité Temporelle/Complétude/Fiabilité) 
- Une décomposition par GES ---> Avec une fenêtre d'aide qui dit à l'utilisateur de mettre la valeur totale dans "CO2" s'il ne connait pas la décomposition - La valeur totale est calculée en sommant les différents GES
- Le(s) poste(s) et le(s) sous-poste(s) du Bilan Carbone® au sein duquel il souhaite que le FE soit disponible
- Les règles de calcul pour les exports sur ce FE -----> Attention, il peut y avoir **une règle par poste/sous-poste** dans lequel le FE est disponible. Si rien n'est renseigné, rien n'est pris en compte dans l'export, un message de warning affiche "Attention, le FE suivant n'est pas pris en compte au sein de vos exports car vous n'avez pas paramétré les règles de calcul associées". À voir comment on fait remplir ça par l'utilisateur à terme, mais pour une V1, sur chaque poste/sous-poste pour lequel on veut que le FE soit dispo, il faut renseigner dans quel poste du BEGES la valeur doit se retrouver pour les différentes caractérisations (2 ou 3 cas différents). **À rediscuter en fonction de comment on gère les exports dans l'outil.**

**Comment by fortinlouis** [comment]
Point 23/10/2024 :
Creation:
  * unité => liste, voir bc+ actuel
  * pas de langue dans la V1
  * sous localisation => 1 seul champs, libre, optionel
  * Classification, en attente de @GChabahABC , en select
  * ajout de gaz SF6, HFC et PFC (attention à l'import de la BE et du SF6, divers dans autre gaz)
  * Par poste, pas d'unité, pas d'incertitude, type: champs libre
  * supression de qualité dans le model actuel
