### ISSUE TITLE
[Investigation] ETQ utilisateur, je peux filtrer les facteurs d'émission

### ISSUE THREAD

**Issue by cmolle** [ABC-TransitionBasCarbone/bilan-carbone#45]
## Contexte
Les utilisateurs veulent parfois pouvoir consulter les facteurs d'émissions disponibles sur l'outil sans forcément être dans une étude. De plus, il leur arrive d'avoir besoin de facteurs d'émissions spécifiques qui ne sont pas disponibles dans les bases de données que nous importons et il faut donc qu'ils aient un endroit pour les créer et les gérer.

Comme il y a plusieurs dizaines de facteurs d'émission il faut que l'utilisateur puisse le filtrer

## Tests d'acceptance
Pas de code donc pas de test pour ce ticket, le but ici est de faire une proposition UX/UI par rapport à ce qu'il est possible de faire avec nos contraintes/objectifs 

- il y a environ 17000 FE dans un import de la base empreinte, sachant que nous allons également devoir gérer une historisation et donc gérer plusieurs dizaine de facteurs d'émission sur cette page.
- Nous allons vouloir filtrer sur plusieurs colonnes (il faudra au moins pouvoir filter sur les libéllés, la source, le détail, le status et la localisation
- Eventuellement, ca pourrait être cool que l'utilisateur puisse choisir les colonnes qu'il souhaite afficher.
    (J'avais vu le datagrid de mui qui avait l'air assez cool, mais du coup ca filtre en front, donc je me dis que c'est pas l'idéal dans notre cas)

**Comment by fortinlouis** [comment]
Point 23/10/2024 :
  * Ajouter la localisation, champs libre fuzzy
  * Integré ou commun
  * pour l'instant on n'affiche que les valide
