### ISSUE TITLE
Page d'accueil pour une organisation

### ISSUE THREAD

**Issue by GChabahABC** [ABC-TransitionBasCarbone/bilan-carbone#6]
## Contexte

Lorsqu'un utilisateur se connecte, il arrive sur la page d'accueil de l'organisation à laquelle il appartient. Cette page d'accueil doit se décliner légèrement en fonction du type d'organisation : 
- Soit l'organisation est un bureau d'étude ou équivalent, c'est-à-dire un adhérent Conseil et Recherche (C&R) de l'ABC. Dans ce cas, le bureau d'étude va effectuer des études sur lui-même (son propre Bilan Carbone), mais aussi sur ses clients. 
- Soit l'organisation ne l'est pas, c'est-à-dire est adhérente dans un autre collège que C&R de l'ABC (Entreprise ; Secteur Public ; Associations, fondation, ONG, autres). Dans ce cas, l'organisation n'est autorisée qu'à effectuer des études sur elle-même.

## Tests d'acceptance 

L'utilisateur classique doit pouvoir accéder à une page d'accueil où il visualise : 
- En haut à gauche, les résultats carbone de la dernière étude effectuée, découpés par poste du Bilan Carbone
- En haut à droite, les résultats carbone au sein d'un des postes du Bilan Carbone, découpés par sous-poste. Un menu déroulant permet de sélectionner le sous-poste à visualiser
- En bas à gauche, les actualités (telles qu'actuellement présentée sur le BC+)
- En bas à droite, les études (telles qu'actuellement présentée sur le BC+)
Les résultats sont repris de l'étude **complète la plus récente** associée à l'organisation. 
Exemple de disposition : ![Image](https://github.com/user-attachments/assets/866b9d8c-fb58-4942-a27b-aa08f1b06445)

L'utilisateur C&R doit pouvoir accéder à une page d'accueil où il visualise : 
- Les actualités, telles qu'actuellement présentée sur le BC+ 
- Les études, groupées par organisation étudiées : Si l'utilisateur a trois clients A, B et C dont il fait le troisième Bilan Carbone, lorsqu'il clique sur l'organisation A (qui doit s'afficher avec son logo), il arrive sur la page dédiée à A, etc. La page dédiée aux organisations est la même que la page d'accueil pour les utilisateurs classiques. 

Les utilisateurs doivent pouvoir ajouter des études ou des organisations en favoris pour qu'elles s'affichent en haut de la liste. 

## Infos de test

Tester en tant qu'utilisateur C&R et en tant qu'utilisateur classique que les deux vues demandées sont bien affichées. 
En tant qu'utilisateur C&R, tester la navigation entre la page d'accueil et les pages organisations lorsque l'on sélectionne une organisation. 

## Stratégie technique 

[...]

**Comment by cmolle** [comment]
@GChabahABC deux petites questions : 
- Pour les graphiques tu veux quel type de grpahique ? Je suppose qu'en abscisse on met les poste, en ordonnée des tCO2 ? Est-ce qu'on fait un barchart, un donut ? (si besoin tu peux regarder ici les différents charts dispo dans la librairie utilisée sur clickson https://www.chartjs.org/docs/latest/charts/area.html) 
- Il me semble qu'on avait parlé du fait qu'avec le rassemblement des études dans un dossier, on allait aussi y mettre à cet endroit là les plans d'actions. Est-ce qu'il ne faudrait pas leur trouver une place sur cette page ?

**Comment by GChabahABC** [comment]
@cmolle 

- Il faudrait qu'ils puissent choisir entre barchart et pie, mais on peut commencer juste avec un barchart pour tout le monde et on intègrera le fait de pouvoir changer de type de graphique après janvier ? Selon le temps que ça prend à dév
- Si, il faudra qu'on rajoute les éléments du plan de transition, je suppose à minima une visualisation de la trajectoire, mais ce sera dans une V2. Est-ce que le plus simple ne serait pas de faire deux onglets sur ces visuels récapitulatifs avec un onglet résultats carbone qui est celui décrit dans le ticket et un autre onglet résultats plan de transition qu'on rajoute dans une V2 ? Sinon j'ai peur que niveau place ce soit chaud sur la page !

**Comment by fortinlouis** [comment]
Reste à faire :
- En haut à gauche, les résultats carbone de la dernière étude effectuée, découpés par poste du Bilan Carbone
- En haut à droite, les résultats carbone au sein d'un des postes du Bilan Carbone, découpés par sous-poste. Un menu déroulant permet de sélectionner le sous-poste à visualiser

**Comment by cmolle** [comment]
Ticket bloqué, en attente du développement de la partie compta carbone

**Comment by cmolle** [comment]
La fin a été codé dans un autre ticket
