### ISSUE TITLE
Pages pour la comptabilisation au sein des différents postes

### ISSUE THREAD

**Issue by GChabahABC** [ABC-TransitionBasCarbone/bilan-carbone#65]
[Ticket en cours de rédaction]

## Contexte

Lorsque l'utilisateur clique sur un poste de l'infographie présente dans la modale accessible via le résumé de l'étude (#64), il arrive sur la page dédiée à la comptabilisation au sein de ce poste. 

## Tests d'acceptance

La page se présente sous la forme suivante (les couleurs, polices etc ne sont pas à garder, c'est simplement un schéma pour la disposition) : ![Image](https://github.com/user-attachments/assets/51b18ab8-ebc8-4836-bea9-f8879f01d934)

En haut, deux encarts permettent d'afficher les graphiques récapitulatifs du poste et le tableau équivalent, pour l'instant ces deux encarts peuvent être ignorés, il faut simplement prévoir la place pour ceux-ci. 

Ensuite, chaque sous-poste est affiché, avec son nom + une description sous celui-ci, pour l'instant les descriptions peuvent être laissées vierges. Les noms des sous-postes sont disponibles ici, pour le fret le nom du poste est "Fret" et les sous-postes "Fret entrant"/"Fret interne"/"Fret sortant" : ![Image](https://github.com/user-attachments/assets/673e77da-b3d2-43a3-a6e7-9e2f2c63d6f8). 

**Différentes interfaces sont disponibles pour cette page. L'utilisateur choisit l'interface voulue via un toggle**. Dans l'idéal, le toggle devrait être le plus accessible possible pour permettre aux utilisateurs de changer facilement d'interface. Il est ensuite possible de cliquer sur les différents sous-postes pour les dérouler, ce qui affiche une des interfaces disponibles. 

**Interface 1 : Premier paramétrage des sources d'émission** > Champs : Statut, Libellé, [Tag] (pour une V2), Caractérisation
**Interface 2 : Données d'activité** > Champs : Statut, Libellé, Contributeur, Date butoir, Valeur donnée d'activité, Unité donnée d'activité, Qualité DA, Source, Type, Commentaire. **Note : Pour certains postes d'émission/sous-postes d'émission, il est possible qu'un champ spécifique supplémentaire soit requis ici (ex : durée d'amortissement pour le poste Immobilisations)**
**Interface 3 : Facteurs d'émission** > Champs : Statut, Libellé, Facteur d'émission, Valeur & unité FE, Qualité FE, Source FE
**Interface 4 : Résultats**  > Champs : Statut, Libellé, Facteur d'émission, Valeur & Unité FE, Valeur DA, Unité DA, Émissions, Qualité, Coche
**Interface 5 : Incertitudes détaillées :** Champs > Statut, Libellé, Émissions, Qualité, Intervalle de confiance = Borne Inf & Borne Sup, Alpha

Si aucune des interfaces ne satisfait l'utilisateur, celui-ci doit pouvoir dérouler la source d'émission pour afficher l'ensemble des informations liées à cette source d'émission, c-a-d tous les champs décrits ici. L'affichage doit se faire d'une manière verticale, potentiellement avec une ligne dédiée à chaque interface évoquée ci-dessus (en supprimant les doublons entre les interfaces, typiquement entre l'interface 4 et 5).

Tous les champs sont décrits ci-dessous : 
![Image](https://github.com/user-attachments/assets/59e48d65-abea-4c1c-a182-4d82b151125c)

**Statut :** Cette colonne affiche le statut de la ligne de calcul. Tant qu'aucune action n'est réalisée, le statut reste vide. Lorsqu'un éditeur attribue certaines lignes à des contributeurs, le statut affiche "En attente" tant que la contribution n'est pas faite. Si la donnée d'activité est remplie, que ce soit via une contribution ou par un éditeur, le statut affiche "À vérifier". Si la coche à droite de la ligne est cochée, le statut affiche "Validé". Ces textes pourront éventuellement être remplacés par des icônes pour alléger. 
**Contributeur :** Cette colonne affiche le ou les utilisateurs devant contribuer sur cette ligne. Le ou les contributeurs seront définis via une page "Gestion des contributeurs".
**Date butoir :** Cette colonne affiche la date butoir de contribution. Celle-ci sera définit via une page "Gestion des contributeurs".
**Libellé :** Ce libellé est à renseigner par l'utilisateur, c'est un champ textuel libre limité à un certain nombre de caractère à définir. 
**Tag** : Cette colonne est une liste déroulante proposant les divers tags renseignés par l'utilisateurs dans la page "Gestion des tags"
**Caractérisation :** Cette colonne est une liste déroulante affichant les différents caractérisations possibles. Ces caractérisations diffèrent légèrement selon le poste et le mode de contrôle, voir cet excel pour référence : **[À créer]**
**Facteur d'émission :** Cette colonne permet de sélectionner un facteur d'émission parmi une liste déroulante de FE déjà présélectionnés pour ce sous-poste. Une icône loupe permet d'ouvrir une modale de recherche plus détaillée, qui doit permettre de trier/filtrer sur les FE prévus pour le sous-poste, et d'aller plus loin en sélectionnant n'importe quel FE présent au sein de la base
**Valeur et unité FE :** Cette colonne affiche l'unité et la valeur du FE sélectionné, si elle peut être fusionné avec la colonne FE côté dév c'est top. 
**Qualité FE :** Cette colonne affiche une qualité globale pour le FE sélectionné, si l'utilisateur hover dessus, les cinq qualités sont affichées. L'utilisateur doit pouvoir modifier ces qualités s'il le souhaite. 
**Source FE:** Cette colonne affiche la source du FE sélectionné ("Base Empreinte®" ou autre source que nous allons ajouter, ou la source rentrée par l'utilisateur lors de la création du FE si c'est un FE personnalisé)
**Valeur donnée d'activité :** Cette colonne affiche la donnée d'activité si celle-ci est saisie par un contributeur à l'avance, l'éditeur doit pouvoir les modifier ou saisir la donnée lui-même si rien n'est saisit.
**Unité donnée d'activité** Cette colonne affiche l'unité de la donnée d'activité. Cette unité est récupérée en fonction du FE sélectionné (exemple, si le FE est en kgCO2e/kg, l'unité est kg, si le FE est en kgCO2e/tonne, l'unité est tonne). Si aucun FE n'est sélectionné, afficher ("Veuillez sélectionner un FE"/"Aucun FE sélectionné").
**Qualité DA :** Cette colonne affiche la qualité sur la DA si celle-ci est saisie par un contributeur à l'avance, l'éditeur doit pouvoir les modifier ou saisir la donnée lui-même si rien n'est saisit. De même que pour les autres champs de qualité, un champ > Si hover, 5 champs.
**Source DA :** Cette colonne affiche la source de la DA si celle-ci est saisie par un contributeur à l'avance, l'éditeur doit pouvoir les modifier ou saisir la source lui-même si rien n'est saisit. Champ textuel limité en caractères **[limite à définir]**.
**Type :** Cette colonne affiche le type de la DA si celle-ci est saisie par un contributeur à l'avance, l'éditeur doit pouvoir les modifier ou saisir le type lui-même si rien n'est saisit. Menu déroulant avec les options suivantes : "Physique" "Comptable" "Extrapolée" "Statistique" "Approchée".
**Commentaire :** Cette colonne affiche un commentaire sur la DA si celui-ci est saisit par un contributeur à l'avance, l'éditeur doit pouvoir le modifier ou saisir un commentaire lui-même si rien n'est saisit.
**Émissions :** Cette colonne affiche les émissions calculées pour la source d'émission. Émission = DA*FE.
**Qualité :** Cette colonne affiche l'incertitude globale sous forme qualitative pour la source d'émission.
**Borne inf & sup :** Dans l'idéal, sont fusionnées en une seule colonne "intervalle de confiance à 95%" affichant [borne inf ; borne sup]
Borne Inf : Cette colonne affiche la borne inférieure de l'intervalle de confiance à 95%. Borne inf = Émission/sigma^2
Borne Sup : Cette colonne affiche la borne supérieure de l'intervalle de confiance à 95%. Borne sup = Émission/sigma^2
**Alpha :** Cette colonne affiche un pourcentage, alpha = (Borne sup - émission)/émission
**Coche :** Cette colonne affiche une coche de validation que les validateurs peuvent cocher. 

Un bouton "Plus" situé sous ou à côté de la dernière ligne complétée doit permettre aux éditeurs et droits supérieurs d'ajouter des lignes de calcul. 

## Infos de test

Vérifier que les dix pages dédiées aux postes sont bien accessibles via l'infographie. 
Vérifier que l'on peut bien ré-accéder facilement à l'infographie depuis les pages des postes.
Vérifier le bon fonctionnement des 5 interfaces disponibles sur ces pages (complétion des champs pour ceux pouvant être complétés ici, reprise des bonnes informations depuis les bases de données (FE notamment). 
Vérifier que l'on puisse bien switcher entre ces 5 interfaces facilement et rapidement. 

## Stratégie technique

[À compléter]

**Comment by desoindx** [comment]
Le coté contributeur a gerer autre part n'est pas clair pour moi

**Comment by GChabahABC** [comment]
PI : Le côté "5 modes d'affichage des infos pour compléter" n'est pas géré pour le moment, à redécouper dans un autre ticket.
