### ISSUE TITLE
Bandeau de navigation

### ISSUE THREAD

**Issue by GChabahABC** [ABC-TransitionBasCarbone/bilan-carbone#7]
## Contexte

Créer un bandeau de navigation pour l'ensemble des pages du BC+, qui remplacera l'actuel situé à gauche de l'écran et les autres bandeaux existants (bas de l'écran actuel, droite de l'écran au sein des études, ...)

## Tests d'acceptance 

Le bandeau actuellement situé à gauche doit être revu graphiquement et se situer en haut de l'écran. L'ordre des boutons est le suivant : 
- Accueil [Redirige vers la page d'accueil]
- Gestion des facteurs d'émission (FE) [Redirige vers la base de FE]
- Gestion de l'équipe [Redirige vers la page actuellement nommée "Répertoire"]
Et tout à droite du bandeau : 
- Support [Redirige vers l'adresse support@abc-transitionbascarbone.fr]
- Mon profil [Redirige vers une gestion du compte utilisateur != compte organisation]
- Langue [Menu déroulant permettant de changer la langue du site]
Les boutons "Outils" et "Formations" devront être rajoutés au bandeau dans le futur. Le bouton "Étude" doit apparaitre sur le bandeau dès lors que l'utilisateur est au sein d'une étude. Hovering sur le bouton "étude" fait apparaitre l'ensemble des fonctionnalités associées à l'étude qui redirigent vers les pages associées : 
- Résumé [Ramène vers la page d'accueil de l'étude]
- Cartographie des flux [Amène vers une page équivalente à celle de l'actuel BC+]
- Gestion, [Déroule un menu avec : Organisation [Amène vers une page de visualisation/modification de l'organisation] ; Équipe Projet [Amène sur un équivalent de la page du BC+ actuel du même nom] ; Documents [Amène sur une page listant l'ensemble des documents importés et leur provenance]]
- Comptabilisation [Déroule un menu dont les pages sont encore à définir, pour le moment les pages actuelles de "Préparation et saisie" + la page "Résultat" peuvent être dans ce menu]. 

Exemple : ![Image](https://github.com/user-attachments/assets/bb588544-cc68-4f98-af3d-124aad30bbdd)

## Infos de test

Vérifier que le bandeau de navigation est présent sur l'ensemble des pages déjà créées, et qu'il est fonctionnel pour les pages existantes.

## Stratégie technique 

[...]

**Comment by cmolle** [comment]
@GChabahABC  j'ai peur que les noms des catégories sur le bandeau soient un peu trop long. On peut tenter comme ca mais si jamais, j'anticipe, est-ce qu'on pourra changer par  : 
- Gestion de l'équipe  --> Equipe 
- Gestion des facteurs d'émission --> Facteurs d'émission 
- Support --> Une icone ❓ 
- Mon profil --> Une icone 👤

**Comment by GChabahABC** [comment]
@cmolle Ok pour les deux premier et le quatrième si besoin, par contre si on peut éviter le "?" uniquement pour support qui n'est pas très clair à mon avis, c'est top ! À la limite "Aide" s'il faut vraiment réduire.

**Comment by fortinlouis** [comment]
Dans la mêne idée de simplifier la barre : Accueil --> Une icone 🏠 ?

**Comment by GChabahABC** [comment]
@fortinlouis Yes, ça me va !

**Comment by fortinlouis** [comment]
@GChabahABC Tu veux que le bandeau soit affiché tout le temps en haut ou qu'il disparaisse en même temps qu'on scroll ?

**Comment by GChabahABC** [comment]
@fortinlouis Hello, plutôt qu'il soit affiché tout le temps !

**Comment by fortinlouis** [comment]
Reste à faire :

Bouton "Étude" ->  Hovering sur le bouton "étude" fait apparaitre l'ensemble des fonctionnalités associées à l'étude qui redirigent vers les pages associées :
Résumé [Ramène vers la page d'accueil de l'étude]
Cartographie des flux [Amène vers une page équivalente à celle de l'actuel BC+]
Gestion, [Déroule un menu avec : Organisation [Amène vers une page de visualisation/modification de l'organisation] ; Équipe Projet [Amène sur un équivalent de la page du BC+ actuel du même nom] ; Documents [Amène sur une page listant l'ensemble des documents importés et leur provenance]]
Comptabilisation [Déroule un menu dont les pages sont encore à définir, pour le moment les pages actuelles de "Préparation et saisie" + la page "Résultat" peuvent être dans ce menu].
