### ISSUE TITLE
Redirection vers les mentions légales

### ISSUE THREAD

**Issue by GChabahABC** [ABC-TransitionBasCarbone/bilan-carbone#8]
## Contexte

Une redirection doit être faite sur l'ensemble des pages vers la page mention légales. 

## Tests d'acceptance 

Un bouton d'accès à la page "Mentions Légales" doit être créé en bas à droite de l'ensemble des pages.  Quand je clique dessus j'arrive sur une nouvelle page avec pour l'instant du texte random. Le texte des CGU sera rajouté par la suite une fois celui-ci finalisé. 

## Infos de test

Vérifier la présence du bouton sur l'ensemble des pages.

## Stratégie technique 

[...]

**Comment by cmolle** [comment]
@GChabahABC Est-ce qu'on a déjà un lien vers les mentions légales ou elles sont à créées ? Qu'est-ce qui fait que tu veux les avoir sur toutes les pages ? Je me demande si ca ne risque pas de surcharger un peu le site et si on ne pourrait pas les mettre sur certaines pages seulement (par exemple : a la connexion, sur la page mon profil et éventuellement sur la page d'accueil). 
Qu'en penses-tu ?

**Comment by GChabahABC** [comment]
@cmolle Une V1 ici, mais on fera probablement valider par un juriste en même temps que les CGU et politique de confidentialité : https://associationbilancarbone.sharepoint.com/:w:/s/AssociationBilanCarbone/EcYIBTyYu0VLtyKQlcGPB1IBWFE3uKLudT-J7ILldD07cw?e=LKFNBO. Ok pour moi si ce n'est qu'à la connexion, j'imaginais un bandeau toujours affiché en bas comme sur pas mal de sites, mais effectivement ça peut être compliqué sur certaines pages en fonction de la place.

**Comment by cmolle** [comment]
Ok merci ! Comme c'est pas la version finale, pour l'instant on va mettre un texte random et on le changera en temps voulu :)

**Comment by cmolle** [comment]
Enfait tu as raison si on le met pas en dessous de toutes les pages il faudrait peut être le rajouter dans une partie "mon compte" de l'appli. Ajoutons le partout et on verra après si ca surcharge trop les pages mais ca devrait aller
