### ISSUE TITLE
Mettre à jour Artifacts

### ISSUE THREAD

**Issue by cmolle** [ABC-TransitionBasCarbone/bilan-carbone#88]
La github action artifactsv3 va être déprécié le 5 décembre, il faut donc qu'on passe rapidement à la v4 car notre ci qui en dépend risque de bientôt ne plus passer (ils ont dit qu'ils feraient failed plus tôt les actions pour préparer les gens au changement). 

Objectif de ce ticket : passer à la v4 de artifacts

**Comment by fortinlouis** [comment]
Documentation : https://github.blog/changelog/2023-12-14-github-actions-artifacts-v4-is-now-generally-available/
