### ISSUE TITLE
[Investigation] Trouver un hébergeur pour stocker tous les fichiers

### ISSUE THREAD

**Issue by cmolle** [ABC-TransitionBasCarbone/bilan-carbone#89]
## Contexte
Les utilisateurs vont vouloir téléverser plusieurs fichiers dans le bc +
- La cartographie des flux s'ils l'ont fait sur un autre logiciel 
- plus globalement, ils peuvent vouloir téléverser tous les fichiers qui leur ont été utile pour rassembler les données d'activités de l'entreprise (excel, images, documents texte...)

A priori il ne devrait pas y avoir de vidéos. 

Ce ticket est un ticket d'investigation au terme duquel on veut un benchmark de différentes solutions ainsi que le choix de la dite solution et l'explication de ce choix

**Comment by fortinlouis** [comment]
Solution 1 : OVHcloud Object Storage
- https://www.ovhcloud.com/fr/public-cloud/object-storage/

- Stockage HDD : 0.007€ HT/mois/Go
- 0.01€HT/Go en download (upload gratuit)

- Stockage SSD : 0.018€ HT/mois/Go
- 0.01€HT/Go en download (upload gratuit)

- doc : https://help.ovhcloud.com/csm/fr-documentation-storage-object-storage?id=kb_browse_cat&kb_id=38e74da5a884a950f07829d7d5c75217&kb_category=b29021c8e5a5edd0f078850a25104df8

**Comment by fortinlouis** [comment]
Solution 2 : Scaleway : https://www.scaleway.com/en/object-storage/
--- 
- Multi-AZ Standard Object Storage	~0.0146€ HT/Go/month
- One Zone - IA Object Storage	€0.012€ HT/Go/month
- transferts gratuits
- tarifs : https://www.scaleway.com/en/pricing/storage/

**Comment by fortinlouis** [comment]
Solution 3 : exoscale https://www.exoscale.com/object-storage/
---
- ~0.020€ HT/Go/mois (<512 To)
- ~0.0135€ HT/Go/mois (512 To<X<1000To)
- 0.02€ / Go download (upload gratuit)
- tarifs : https://www.exoscale.com/pricing/#storage

**Comment by fortinlouis** [comment]
Solution 4 : Outscale (conseillé par scalingo) : https://docs.outscale.com/fr/userguide/%C3%80-propos-d-OOS.html
---
- 0.025€ HT/Mois/Go
- trafic gratuit
- tarifs : https://en.outscale.com/pricing/
- doc : https://docs.outscale.com/fr/userguide/Stockage.html

**Comment by cmolle** [comment]
@fortinlouis est-ce que tu as regardé un peu la doc à quel point ca avait l'air facile d'utiliser l'un ou l'autre ? (typiquement celui conseillé par scalingo, est-ce que du coup ca rend l'utilisation plus facile ?) 
Est-ce que tu sais à quel point chacun est utilisé/conseillé ?

**Comment by fortinlouis** [comment]
@cmolle Je n'ai jamais utilisé de stockage type s3 dans mes projets, donc je n'ai pas l'expertise sur la pertinence de chaque solution.

Ce que je peux te dire : 
- J'ai inclus OVH dans le sujet car un peu obligé au vu de la taille de l'entreprise. Mais d'expérience, ils ne propose pas du tout la meilleur UX.
- J'ai également inclus Outscale car conseillé par scalingo, mais la doc n'est pas très user-friendly alors ça n'est pas le genre de solution qui m'attire. 
- Parmi toutes les pages que j'ai consulté, la plupart conseillaient scaleway, c'est peut-être vers celle là que je m'orienterais

**Comment by cmolle** [comment]
Ok, en regardant rapidement, scaleway ca me parait bien en vrai. Je pense qu'on peut partir là dessus.
